### ISSUE TITLE
Update to Node 8

### ISSUE THREAD

**Issue by pascalandy** [docker-library/ghost#102]
Since Ghost 1.16.2, the Ghost project requires using Node 8. 
https://github.com/TryGhost/Ghost/releases/tag/1.16.2

I'll test this and will do a PR.

**Comment by acburdine** [comment]
Just a note so there’s no confusion: the latest version of ghost doesn’t _require_ node 8, but it is _compatible_ with node 8 😉. Node 6 is still the recommended version: https://docs.ghost.org/v1/docs/supported-node-versions

**Comment by pascalandy** [comment]
I guess I got confused when I read:

> We've bumped the minimum required version for Node v8

**Comment by acburdine** [comment]
Yeah, sorry about that 😅. In 1.16.1, the minimum supported version of _node 8_ (eg not node 4 or 6), was 8.8.x - 8.9 became the official LTS release, hence the update. The release message was worded a bit oddly, but that’s what happened.

**Comment by acburdine** [comment]
Gonna go ahead and close this since node 6 is still the recommended version of node for Ghost.

**Comment by pascalandy** [comment]
A while ago, I saw a grid about which Node version is the recommended one for Ghost. It was also referring the LTS support. Would make sense to refer to it :)
