### ISSUE TITLE
no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by jihchi** [docker-library/ghost#106]
I got following error when pulling ghost image:

```
no matching manifest for linux/amd64 in the manifest list entries
```

Is this relative to https://github.com/docker-library/official-images/issues/2289 ?

my environment:
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

**Comment by ScarletWolf275** [comment]
This is completely normal. You were trying to run the v1.17.3 image, which was new at the time. An updated version of this image was released the next day which hopefully fixed the image for you.

**Comment by tianon** [comment]
See also docker-library/rabbitmq#188, docker-library/ruby#159, c0b/docker-erlang-otp#75, and docker-library/official-images#3472, https://github.com/docker-library/wordpress/issues/239, https://github.com/piwik/docker-piwik/issues/70, https://github.com/nodejs/docker-node/issues/571, https://github.com/docker-library/official-images/issues/3653, https://github.com/docker-library/official-images/pull/3622#issuecomment-339838650. :+1:

**Comment by tianon** [comment]
I've filed https://github.com/docker-library/official-images/issues/3835 in order to have a central place to track this problem globally more directly. :+1: :heart:
