### ISSUE TITLE
How to mount /var/lib/ghost to somewhere on the actual disk.

### ISSUE THREAD

**Issue by ScarletWolf275** [docker-library/ghost#108]
Hello. I'm trying to access Ghost's core. Not just the content folder, the core itself but that seems impossible! I can't do it, no matter what. I get an error with content.orig not found and all that and I guess it is because the image is not supposed to mount /var/lib/ghost. But I need /var/lib/ghost. I want to freely be able to edit the core. Thanks

**Comment by eexit** [comment]
Hey, this may help: https://github.com/docker-library/ghost/issues/76#issuecomment-345987646

**Comment by pascalandy** [comment]
Look at the docker volume section over https://hub.docker.com/_/ghost/

The example is solid :)

**Comment by acburdine** [comment]
@ScarletWolf275 It is simple enough to extend the base dockerfile and make the volume mountable yourself. Something like this would work:

```dockerfile
FROM ghost:alpine

VOLUME /var/lib/ghost/current/core/
```

Gonna close this though, as making the core directory mountable is (imo) something that very few people would use, and somewhat goes against the purpose of Docker images themselves.

**Comment by slaklad** [comment]
@pascalandy you arrogant pussy. You never answer a question in clear terms. You think you're the smart guy but you're shit. If you don't want to help stay put you piece of shit.

**Comment by tianon** [comment]
Please keep the discourse positive; that's a pretty awful thing to say to someone who's trying to help, especially on their own time, and won't be tolerated here.
