### ISSUE TITLE
Tracker Data

### ISSUE THREAD

**Issue by karai17** [docker-library/ghost#110]
When I use this public api on my main website that pulls data from a blog i have running on this image, I get several attempts at injection from some blog spam site, http://blogtoplist.com/

![image](https://user-images.githubusercontent.com/590332/33143531-8a4cdbae-cf90-11e7-958d-2443c56047d2.png)

Any idea what's up with this? I'd really appreciate if this wasn't happening... I've deployed several blogs for clients and they all have this same issue.

**Comment by SISheogorath** [comment]
Please check the official ghost support. Their slack channel can answer this question for sure.

Since it's not docker specific, this is the wrong place for this question.

No matter what, the keywords you search for is ghost and CSP. Maybe the docs already point you into the right direction.

**Comment by acburdine** [comment]
@karai17 gonna close this because it isn’t related to Docker. My guess is those requests are coming from your theme - nothing in Ghost itself does this.

**Comment by karai17** [comment]
My theme is 100% custom made, not even based on another theme, so I don't think that is the case. It seems to be coming from the Public API. I'll ask in the ghost repo, though.
