### ISSUE TITLE
npm echo Error 'Segmentation fault'

### ISSUE THREAD

**Issue by yuhr123** [docker-library/ghost#111]
Hi there! 

My operating system is `Alpine Linux 3.6.2-extend_x86_64` and docker-ce version is 17.07.0-ce.

Any other container is running ok, but nodejs related images(container) not. 

When I create a ghost blog container with [library/ghost](https://hub.docker.com/_/ghost/) image, it will give a error echo `Segmentation fault` and the ghost container always can not start.

I create and into a nodejs contianer found that any command related npm like `npm -v` will echo 'Segmentation fault'.

There is a log fragment by another user who has the same problem. [log fragment](https://gist.github.com/Xe/f0d7f5a54175f2242c7df807b3a08dbb)

**Comment by yosifkit** [comment]
This looks like https://github.com/nodejs/docker-node/issues/588.

**Comment by yuhr123** [comment]
@yosifkit Thank you! 
Yes, it is the same problem and I fix it by build a new image with a Dockerfile:

```
FROM ghost:alpine
RUN apk add --no-cache paxctl && paxctl -cm `which node`
```

This issue should close, but I want to konw is it the `paxctl` will be added to the ghost officail image in the feature?
