### ISSUE TITLE
make url configurable via env var.

### ISSUE THREAD

**Issue by rucuriousyet** [docker-library/ghost#113]
This docker image works for almost everything, but in order to get a fully working website, you need to be able to change the host url... ideally this should be something that can be configured via env var. I may submit a PR for this in the near future...

**Comment by tianon** [comment]
This is already supported via "-e url=..."

**Comment by rucuriousyet** [comment]
Good to know... Is it in the docker doc?

-sent from my OnePlus X

**Comment by tianon** [comment]
```yml
...
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
...
```

(from https://hub.docker.com/_/ghost/)
