### ISSUE TITLE
Mount config files in volumes

### ISSUE THREAD

**Issue by clementduveau** [docker-library/ghost#118]
Config file config.production.json is not mountable in a volume. This make the container mutable and it's against Docker.

Why is it like it ?
Should we modify it ?

**Comment by tianon** [comment]
You need to be more specific about what you've tried and what didn't work.

Generally, we recommend supplying configuration to this container via the Ghost-supported environment variables (avoiding the need for a file at all; https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables), but we have quite a few users who are successfully using their own configuration files.  See https://github.com/docker-library/ghost/issues/116 for a recent example.

**Comment by clementduveau** [comment]
Thanks for your reply. I understand now how it works for Ghost.

I was expecting to have my config file in a volume. But environment variables achieve the same feature: use the same command to create a new identical container (or update). Usually, on others containers, I use a volume for data and a volume for config files.

Thanks for your time
