### ISSUE TITLE
Cant change url for prodcution

### ISSUE THREAD

**Issue by skindc** [docker-library/ghost#123]
It seems in you docker file that you are setting the url for the ghost server to http://localost:2368.

How are you supposed to change this?, setting up the config does not seem to have any affect.

**Comment by tianon** [comment]
Set "url" as an environment variable on your container and it'll overwrite
the value in the config.

**Comment by acburdine** [comment]
@skindc An explanation on how to do this can be found in the Ghost docs: https://docs.ghost.org/v1/docs/config/#section-running-ghost-with-config-env-variables

Closing this as there's a defined way to set config values and this isn't a bug 😄

**Comment by skindc** [comment]
Hi,

Im so sorry, I had read all of this and has everything I need to do this. It was very late and I was too quick to post.
Just a quick note for anybody else, if you are using a docker-compose.yaml file you can do set the any of the environment variables mentioned in the docs mentioned by acburdine using declarations like so.

service:
    ...
    environment:
        -  url=https://blog.skindc.co.uk
    ...

Also if you are using Nginx and ssl as a seperate service in in the docker composition ensure you set  the following header on the proxy.

proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
