### ISSUE TITLE
When enable SSL in nginx and set URL (-e url=xxx) ,it says"Too many redirects"

### ISSUE THREAD

**Issue by jsdfly** [docker-library/ghost#128]
How should I deal with it?

**Comment by wglambert** [comment]
Without specifics, resources I've found that might relate to this issue:

https://serverfault.com/questions/839779/nginx-err-too-many-redirects-error-after-ssl-configuration
https://www.digitalocean.com/community/tutorials/understanding-nginx-http-proxying-load-balancing-buffering-and-caching

If it's a proxy_pass issue, it seems connections to the server are being redirected to itself repeatedly. Are you using proxy_pass in your config?

**Comment by jsdfly** [comment]
@wglambert Well...my ghost.conf under /etc/nginx/conf.d is below (I nearly forgot showing it...):


server {
    listen 443 ssl http2;
    ssl on;
    server_name xxxxx.xxx;
    ssl_certificate /etc/nginx/ssl/*.xxxxx.xxx.cer;
    ssl_certificate_key /etc/nginx/ssl/*.xxxxx.xxx.key;
    add_header Strict-Transport-Security max-age=31536000;
        location / {
        proxy_set_header    X-Real-IP   $remote_addr;
        proxy_set_header    Host              $http_host;
        proxy_pass         http://127.0.0.1:80xx;
}
}
server {
    listen 80;
    server_name xxxxx.xxx;
    add_header Strict-Transport-Security max-age=31536000;
    return 301 https://xxxxx.xxx$request_uri;
}


What is wrong with it?
I tried to cancel ssl in nginx and use Cloudflare's service which has built-in ssl,and the site works normally...

**Comment by jsdfly** [comment]
@wglambert 

Now:
Nginx+Docker-Ghost **Works**
Nginx+Docker-Ghost-With-URL"http**s**://xxxxx.xxx"+Cloudflare **Works**

Nginx-SSL **Works** with 502
Nginx-SSL+Docker-Ghost-With-URL"http**s**://xxxxx.xxx" **NOT WORKING:TOO MANY REDIRECTS**

It seems that something is wrong with my configuration file...It is my first time to use Nginx...

Thanks for your help...

**Comment by tianon** [comment]
I think you need to include `X-Forwarded-Proto` in your NGINX configuration (which CloudFlare also sends appropriately).  See also https://github.com/TryGhost/Ghost/issues/2796.

Since this is a configuration issue (not something wrong with the image itself), I'm going to close. :+1: :heart:
