### ISSUE TITLE
Wrong entrypoint.sh 

### ISSUE THREAD

**Issue by MocanuMarius** [docker-library/ghost#13]
Hey guys, your entrypoint.sh is wrong, as it copies only folders and config.js is not properly copied . Then it checks if it exists, and replaces it with config.example.js . Of course it's not gonna be there since it only copies folders, so hence you cannot modify config.js at all

**Comment by tianon** [comment]
I'm not sure what you mean?  We copy contents from `GHOST_SOURCE/content` if they're missing in `GHOST_CONTENT`, and `config.js` doesn't exist in `GHOST_SOURCE/content`:

```console
root@a979242c6a39:/usr/local/ghost# ls -l content/
total 0
drwxr-sr-x 1 root staff 18 Jan 12 17:58 apps
drwxr-sr-x 1 root staff 18 Jan 12 17:58 data
drwxr-sr-x 1 root staff 18 Jan 12 17:58 images
drwxr-sr-x 1 root staff 12 Jan 12 17:58 themes
```

Additionally, we create `GHOST_CONTENT/config.js` based on `GHOST_SOURCE/config.example.js` if and only if `GHOST_CONTENT/config.js` does not already exist.

**Comment by MocanuMarius** [comment]
Exactly, only that config.js won't be ever copied for me in GHOST_SROUCE/content

**Comment by tianon** [comment]
It's not supposed to be; it's supposed to be copied into `GHOST_CONTENT`.  Your modifications need to happen either in the `GHOST_SOURCE/config.example.js` file (if you want them to apply on the initial start of Ghost), or in `GHOST_CONTENT/config.js` after the container is started and the file is initialized by the entrypoint.

**Comment by MocanuMarius** [comment]
I'm not sure what you mean, but explain to me how should i bootstrap my application to run on another port, other than the default one 2368, if i modify that in config.js , the changes are not made because exactly as you said above, it copies example.config.js , so the actual config.js that i modify in my docker volume has no effect.

**Comment by MocanuMarius** [comment]
Let's go over the code

    if [[ "$*" == npm*start* ]]; then
      for dir in "$GHOST_SOURCE/content"/*/; do
        targetDir="$GHOST_CONTENT/$(basename "$dir")"
        mkdir -p "$targetDir"
        if [ -z "$(ls -A "$targetDir")" ]; then
          tar -c --one-file-system -C "$dir" . | tar xC "$targetDir"
        fi
      done

      if [ ! -e "$GHOST_CONTENT/config.js" ]; then
        sed -r '
          s/127\.0\.0\.1/0.0.0.0/g;
          s!path.join\(__dirname, (.)/content!path.join(process.env.GHOST_CONTENT, \1!g;
        ' "$GHOST_SOURCE/config.example.js" > "$GHOST_CONTENT/config.js"
      fi

-For eah directory in GHOST_SOURCE, copy into GHOST_CONTENT ( IMPORTANT: Only directories) 
-Hence config.js from GHOST_SOURCE won't be copied into GHOST_CONTENT
- In the next lines, if config.js doesn't exist in the destination folder, then use example.config.js
=> Hence config.js won't ever be used if i modify it in my initial source folder

**Comment by yosifkit** [comment]
Where are you putting your config.js?  If you put it in `$GHOST_CONTENT` as `config.js` it will work perfectly, but if you want the entrypoint script to apply the `sed`, then put it in `$GHOST_SOURCE` as `config.example.js` and it will apply the `sed` and put it into `$GHOST_CONTENT`.
