### ISSUE TITLE
url setting

### ISSUE THREAD

**Issue by msmcgillis** [docker-library/ghost#132]
Would be nice to support:

```
ENV GHOST_URL http://localhost:2368
...
u-exec node ghost config --ip 0.0.0.0 --port 2368 --no-prompt --db sqlite3 --url $GHOST_URL --dbpath "$GHOST_CONTENT/data/ghost.db"; \
```

so then one can:

```
$ docker run -e GHOST_URL=http://test.domain.com  ...
```

so you can control the proper server name without going in and adjusting the docker config file.

**Comment by SISheogorath** [comment]
Seems like this idea pops up weekly and no one gets that it's already there. Natively in ghost itself:

https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables

Related issue: https://github.com/docker-library/ghost/issues/77

**Comment by msmcgillis** [comment]
So it is:

```
docker run -e url=http://test.domain.com ...
```

My 2c would be reference your above URL from https://hub.docker.com/_/ghost/  with a note about ghosts native support for additional environment variable.

**Comment by msmcgillis** [comment]
Your url is on the page but not currently clickable and it was not exactly in a context that made me think oh ghost supports a bunch of other environment values let me see what they are. Thanks for the pointer.
