### ISSUE TITLE
Knex dependency in LTS 0.11.13 does not handle reconnections to Remote MySQL Databases causing infinite loading response from Ghost services.

### ISSUE THREAD

**Issue by necevil** [docker-library/ghost#133]
You can see more discussion on the core problem for Knex discussed over here:
https://github.com/tgriesser/knex/issues/1833#issuecomment-394799158

That being said I am opening an issue here since anyone running Ghost LTS (0.11.13) inside of Docker on top of Azure AKS may run into the issue.  This may be particularly relevent since others (like my team) may also be migrating there from Docker Cloud.

I can't replicate the issue locally either but in production on Azure AKS the client -> database connection is some how interrupted.  See my question on StackOverflow looking for WHY that connection is broken:   https://stackoverflow.com/questions/50706483/what-azure-kubernetes-aks-time-out-happens-to-disconnect-connections-in-out

My GUESS is that this happens at the same time that the Azure Kubernetes Browser UI disconnects / times out. For AKS users who find this in the future you can run the browse ui with:
az aks browse --resource-group <resource-group> --name <cluster-name>

Essentially after 5 minutes or so of Idle it looks to me like all connections pointing out of the Cluster are closed. That in theory would include both the connection to local UI Browse proxy (mentioned above) which gives something like the following read out in console:
E0605 13:29:52.670555 5586 portforward.go:178] lost connection to pod

My hypothesis is that this is also the same time that the Knex connection to my MySQL backend is severed, which then triggers the infinite loading Ghost behavior discussed above... and an eventual 504 Gateway Time-out from whatever you are using to front your Ghost service.

Since it is based on Idle it is a HUGE pain to figure out what is going on.  Obviously moving to Ghost 1.x is an option for some, but if you are running a more production style LTS 0.11.x install and are planning to move to Azure (and possibly other Managed Kubernetes Services) you are probably going to deal with the problem.

# Partial Solution
The 'solution' that initially let me keep my production environment running was to set the MySQL server to terminate connections SOONER than the client connection is severed. Since my Ghost Service is trying to continue using the connection (and expects it to stay open) this is not an issue of closing it when I am done (since I am not).

So even though the Knex client thinks the connection should still be open, having the server CLOSE it on that side before it is severed by the container network timeout kept me from showing Error 503 to customers while I sorted the whole thing out.

# Real Solution
The REAL solution is credit to @cloutiertyler which is rebuilding the Ghost docker image with a rolled back version of  Knex 12.6.  At which point the re-connection functionality works normally.

The lines I added to my docker file were:
```
# Delete Knex 0.12.9 and roll back to 0.12.6
RUN rm -rf node_modules/knex
RUN npm install knex@0.12.6
```

According to the issue over on Knex it sounds like some users have the same problem with other DBs (ie. Postgres) so this may need to be addressed for Ghost user running that database as well.  

# Limited Case
Since the actual cause of the disconnection appears to be at least Kuberetes and maybe specifically Azure AKS, this is a pretty limited case but I figured I would post my findings thus far to HOPEFULLY reach someone seeing the issue in the future.

**Comment by tianon** [comment]
Wow, this is a strange one -- nice debugging work!  Since this is mostly a PSA, I'm going to close, but I think it's good to have this detail out here so that hopefully it'll be helpful to folks running into similar issues with AKS and Ghost 0.x in the future (as you've noted). :+1:

**Comment by necevil** [comment]
@tianon Thanks! Keep up the good works!

**Comment by kibertoad** [comment]
@necevil Is Ghost still using a knex 0.12.x? Was the issue ever resolved?

**Comment by necevil** [comment]
@kibertoad I think they updated but let me be sure before we stop worrying about it.

I think this was only for Ghost LTS 0.11.x which is being phased out in / around November I believe.  That doesn't mean it's not still an issue but worst case scenario it won't be as widely used after being depreciated.
