### ISSUE TITLE
How to use the new override method?

### ISSUE THREAD

**Issue by delta24** [docker-library/ghost#14]
When I used to run `dockerfile/ghost`, I could easily use the `ghost-overide` directory for symlinking the content folder to my containerised blog.
Yesterday I upgraded it to use the new official ghost docker image, and all hell breaks loose. The path to ghost installation has changed, and there is no documentation on how to override except issue #6 which is equally vague.
And the official method to override using `-v /path/to/blog/:/var/lib/ghost/` simply doesn't work.
How do I fix this?

**Comment by yosifkit** [comment]
Does https://github.com/docker-library/ghost/issues/7 help?  If you have a `config.js` in there, you may need to apply the same `sed 's!path.join\(__dirname, (.)/content!path.join(process.env.GHOST_CONTENT, \1!g;'`

**Comment by delta24** [comment]
Hi, isn't there a more simpler method like just overriding the `ghost/content` directory?
But also I couldn't understand you. Can you shed some light on your previous comment?

Thanks!

**Comment by yosifkit** [comment]
If you run with `-v /my/blog/:/usr/src/ghost/content`, then your stuff would be copied by the startup script over to `/var/lib/ghost` in the container.  So yes it would run, but it would not reflect any changes into your bind mounted code.

If you use `-v /my/blog/:/var/lib/ghost` the startup script will check in `/var/lib/ghost/` for each of the directories (apps, data, images, and themes) and copy from `/usr/src/ghost/content` the ones that don't exist.  It then also checks for `config.js` in `/var/lib/ghost/`, and if it does not exist, copies `/usr/src/ghost/config.example.js` while running the above sed to fix the paths in the config.

**Comment by delta24** [comment]
Hi, I am still getting errors.

```
> ghost@0.6.3 start /usr/src/ghost
> node index

ERROR: Unable to access Ghost's content path:
  ENOENT, no such file or directory '/var/lib/ghost/content/apps'

Check that the content path exists and file system permissions are correct.
Help and documentation can be found at http://support.ghost.org.
```

**Comment by pascalandy** [comment]
This conversation died. We should close this conversation.

https://github.com/docker-library/ghost/issues/25#issuecomment-247216227
