### ISSUE TITLE
Proposition for a cleaner ENV section in the Dockerfile

### ISSUE THREAD

**Issue by pascalandy** [docker-library/ghost#141]
Hey guys,

Would you consider putting most ENV all together? I think it's cleaner :)
If so, I'll do a PR

```
ENV GHOST_VERSION="1.25.4"                      \
    GHOST_CLI_VERSION="1.8.1"                   \
    GHOST_INSTALL="/var/lib/ghost"              \
    GHOST_CONTENT="/var/lib/ghost/content"      \
    NODE_ENV="production"
```

Cheers!
Pascal

**Comment by tianon** [comment]
It doesn't make a difference in the actual pushed content (Docker combines
them automatically), so I'd rather not.

**Comment by pascalandy** [comment]
Alright. Let's close this then.
