### ISSUE TITLE
Ghost 2.0 release

### ISSUE THREAD

**Issue by weipah** [docker-library/ghost#142]
Hi everyone,

Ghost 2.0 has been released now.

Will this be added to the docker-library as well, possibly with an upgrade path?

Cheers,
Mark

**Comment by acburdine** [comment]
@weipah Ghost 2.0 didn't contain nearly as many breaking changes as Ghost 0.x => 1.x did, so the upgrade process _should_ be fairly trivial. I'll work on getting a 2.0 image created sometime this week.

**Comment by BirkhoffLee** [comment]
Thank you @acburdine :)

**Comment by voigt** [comment]
Hi,
just send [this](https://github.com/docker-library/ghost/pull/144) PR.
Not sure if @acburdine would do it differently - it works for me 👍🏻
