### ISSUE TITLE
Why is the ghost installed to /var/lib/ghost instead of var/www/ghost as recommended on docs.ghost.org?

### ISSUE THREAD

**Issue by jonoberg** [docker-library/ghost#149]

**Comment by tianon** [comment]
I believe the initial version of our image was created before that recommendation was made, but it's also a bit buried (I had to dig all the way to https://docs.ghost.org/docs/install#section-install-ghost-via-the-cli before I found it).

I don't think it makes much functional difference, does it? (the software runs the same way no matter where you install it)

**Comment by acburdine** [comment]
Prior to Ghost 1.0 there wasn't an "recommended" place to install Ghost on the filesystem. And @tianon is correct - it doesn't make much of a functional difference. Something to note too is that changing it now would technically be a "breaking" docker image change, which wouldn't be a great experience for most people.

Might be something to consider for Ghost 3.0 (whenever that happens, may not be for awhile), but at the moment I don't see much point in changing it.
