### ISSUE TITLE
Image only works on localhost

### ISSUE THREAD

**Issue by kav** [docker-library/ghost#151]
The config files don't appear to allow overriding the host parameter via an easily accessible docker parameter (env vars perhaps?) so the home link misfires if you run the container non-locally

**Comment by kav** [comment]
Looks like #86 addresses this so perhaps this a documentation issue?

**Comment by tianon** [comment]
Yeah, the image definitely don't "only work on localhost" -- the default for the `url` configuration parameter is `localhost`, but it's trivially overridable via environment variable (as are all other configuration options).  It probably does make sense for us to be more explicit about that in the image documentation (https://github.com/docker-library/docs/blob/master/ghost/content.md).

**Comment by tianon** [comment]
Filed https://github.com/docker-library/docs/pull/1306 to help clarify this. :+1:
