### ISSUE TITLE
Setting ENV server localhost:2368 not working

### ISSUE THREAD

**Issue by outluch** [docker-library/ghost#152]
Hi, I am deploying ghost in docker.
By default it listens `0.0.0.0:2368`. It is not good, I wanna use nginx to `proxy_pass`.
I try to set `server` env variable and recreate container, but getting weird beavior
I have `INFO Your blog is now available on http://localhost:2368/ ` in log,
but run `sudo netstat -ntlp | grep LISTEN` and get this
`0 :::60068                :::*                    LISTEN      28166/node`
And it is again accessible from everywhere and with this weird port..
Is it bug?

**Comment by wglambert** [comment]
The container has 2368 open by default only for containers, it will be routable on that port for the host and everything external by specifying `-p 2368:2368`. 
If your nginx is in a container you can connect the two by placing them on the same docker network, or by `--link`ing them.

`netstat -tlpn` doesn't show what process that port is mapped to, doing a `docker ps` is probably what you want and netstat will verify that port.

```console
$ docker run --rm -d -p 31337:2368 --name ghost -it ghost
123a99be59223d090fde7ab1203f13ba66551619b09a7d5e6bc810a6c671d340
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                     NAMES
123a99be5922        ghost               "docker-entrypoint.s…"   3 seconds ago       Up 2 seconds        0.0.0.0:31337->2368/tcp   ghost
$ curl localhost:31337
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <title>Ghost</title>
    <meta name="HandheldFriendly" content="True" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
. . .
```


On networking in Docker https://docs.docker.com/config/containers/container-networking/

**Comment by outluch** [comment]
I appreciate your answer, thanks!
