### ISSUE TITLE
Can't start container with stateful volume

### ISSUE THREAD

**Issue by drewblay** [docker-library/ghost#154]
Tried on CentOS 7 and on Fedora Atomic. Ran command as root, and as a user in the docker group, no difference. 

docker run --name myghost -p 80:2368 -v /root/tmp:/var/lib/ghost/content ghost:alpine

chown: /var/lib/ghost/content: Permission denied

**Comment by wglambert** [comment]
Can't reproduce the issue, might be SELinux related

```console
$ sudo docker run -dit --name myghost --rm -p 80:2368 -v /root/tmp:/var/lib/ghost/content ghost:alpine
Unable to find image 'ghost:alpine' locally
alpine: Pulling from library/ghost
4fe2ade4980c: Already exists 
eeb7d76f44e7: Pull complete 
e35f88fcc259: Pull complete 
b4d59ef07366: Pull complete 
dcee404d51ae: Pull complete 
f0d2c5f09664: Pull complete 
537f043c980b: Pull complete 
fed1e5231176: Pull complete 
Digest: sha256:85a4edefbb52d7022b3f4bbb755cf789f6b82b3111989f4f07727399febd668e
Status: Downloaded newer image for ghost:alpine
015f44563c67fc220631159b72a49d6a61b2476f9fccfe5eca1b57f90b19dcc9

$ sudo ls /root/tmp
apps  data  images  logs  settings  themes
```

**Comment by paolomangiadev** [comment]
> Tried on CentOS 7 and on Fedora Atomic. Ran command as root, and as a user in the docker group, no difference.
> 
> docker run --name myghost -p 80:2368 -v /root/tmp:/var/lib/ghost/content ghost:alpine
> 
> chown: /var/lib/ghost/content: Permission denied

i have the same problem on fedora 28
