### ISSUE TITLE
it can't run in production mode

### ISSUE THREAD

**Issue by LomotHo** [docker-library/ghost#160]
when I set "--env NODE_ENV=production", the container will crash
I use the ghost:0.11-alpine version 
and here is the log 

```
> ghost@0.11.13 start /usr/src/ghost
> node index
ERROR: Unable to access Ghost's content path:
  EACCES: permission denied, open '/usr/src/ghost/content/apps/9d472f697f497e44'
```

**Comment by LomotHo** [comment]
now I have solved the problem, just add this to the config.js in the production part, 

``` json
    production: {
        url: 'http://www.xxxxxxx.com',
        mail: {},
        database: {
            client: 'sqlite3',
            connection: {
                filename: path.join(process.env.GHOST_CONTENT, '/data/ghost.db')
            },
            debug: false
        },
        server: {
            host: '0.0.0.0',
            port: '2368'
        },

    // ===========add this as follow===========
        paths: {
            contentPath: path.join(process.env.GHOST_CONTENT, '/')
        }
    // ===========add this===========
    }
```

**Comment by wglambert** [comment]
Similar https://github.com/docker-library/ghost/issues/15 https://github.com/docker-library/ghost/issues/2 

It looks like prior to version 1.0 the Ghost env variables weren't supported https://github.com/docker-library/ghost/issues/124 https://github.com/docker-library/ghost/issues/73#issuecomment-320196108
The documentation doesn't specify a version requirement https://docs.ghost.org/concepts/config/#section-running-ghost-with-config-env-variables

From [this comment](https://github.com/docker-library/ghost/issues/124#issuecomment-368501232) specifically it seems when using version 0.x you need to configure it using a custom json config

**Comment by tianon** [comment]
Indeed -- I'd really recommend upgrading to Ghost 1.x ASAP, but if you can't, you'll have to deal with JSON files for configuration, unfortunately.

**Comment by tianon** [comment]
@acburdine do you anticipate that there will be any more Ghost 0.x releases?  Should we remove it from the supported images?  What about 1.x? Is the table at https://docs.ghost.org/faq/upgrade-to-ghost-1-0/#why-upgrade-to-1-0 accurate?  There don't seem to have been any releases of either 1.x or 0.x since 2.0.0. :sweat_smile:

**Comment by LomotHo** [comment]
0.x is ok for me. in fact I don't like the default theme of both 1.x and 2.0.  Json config file won't cost so much time...I use systemd to mange the ghost blog before, 
 while docker even cost more time to deploy 0.x.
