### ISSUE TITLE
Ghost officially supports Node V10

### ISSUE THREAD

**Issue by pascalandy** [docker-library/ghost#163]
Since [Ghost 2.5.0](https://github.com/TryGhost/Ghost/releases/tag/2.5.0), the Ghost team officially supports Node V10. Let me know you guys would like a PR.

Cheers!

**Comment by frenchvandal** [comment]
Node v8 LTS is still the recommended version (Node v6 Boron LTS and Node v10 Dubnium LTS are supported).

https://docs.ghost.org/faq/node-versions/

**Comment by acburdine** [comment]
Yup, given that the recommended version is still v8, that's the version the docker image should be based on imo.

**Comment by pascalandy** [comment]
OK then! When I see that, I concluded that V10 was the new base version for Ghost

![screen shot 2018-11-22 at 10 52 12 am](https://user-images.githubusercontent.com/6694151/48912872-c7ad2480-ee44-11e8-991e-8a8167ed61a2.jpg)

**Comment by acburdine** [comment]
@pascalandy yeah that message was a bit confusing. What it should have read was something more like “bump allowed minimum version of node 10 to v10.13.0”

**Comment by pascalandy** [comment]
Thanks for the clarification. I'll close this then.

See ya!
