### ISSUE TITLE
SSL support doesn't work

### ISSUE THREAD

**Issue by buremba** [docker-library/ghost#165]
I try to use the Docker image in order to setup Ghost in our subdirectory using reverse proxy. Here is how I start the container:

`docker run -d --name some-ghost -p 8080:2368 -e url=https://rakam.io/blog ghost`

When I try to access `https://oursite.io/blog` it redirects me to `https://35.246.178.69/blog` which doesn't have SSL support since it's just the IP of the host. However; when I use the following one:

`docker run -d --name some-ghost -p 8080:2368 -e url=http://rakam.io/blog ghost`

It works as expected. Is this a bug or am I missing something?

**Comment by pascalandy** [comment]
This is not an issue with the docker image. Many people use their website over SSL with this docker image. I would argue something is wrong with your setup.

**Comment by tianon** [comment]
From what I can find (both by playing with `ghost setup ssl`, and by exploring the Ghost documentation), Ghost itself doesn't actually support SSL directly, and instead they recommend (and their tools can help configure) terminating SSL in a reverse proxy like NGINX or Apache, which seems pretty reasonable (especially for a production deployment, where you likely want a reverse proxy in front of Node.js anyhow).
