### ISSUE TITLE
Timeline on Ghost 2.8?

### ISSUE THREAD

**Issue by necevil** [docker-library/ghost#173]
Hey guys,
We base our images off of your work (awesome!) and some fixes just hit in 2.8 (https://github.com/TryGhost/Ghost/releases/tag/2.8.0) that we have been struggling with.  

I had two questions:

1. The docker hub tags (https://hub.docker.com/_/ghost/) currently list nothing after 2.14 but we are currently building from 2.7.1 — I was wondering if I am bugged / cached some how, or did you guys dis-allow those tags / images?
2. Any idea when the Alpine image will be updated to utilize 2.8?

I suppose it is probably more complicated than just changing the ENV variable from GHOST_VERSION 2.14.0 to Ghost 2.8?  Thanks again for the work on the ghost front.

**Comment by wglambert** [comment]
For your first question, the tags on the main page show the latest ones, for older tags see https://hub.docker.com/_/ghost/?tab=tags&page=2
There's also https://github.com/docker-library/repo-info which contains all previous versions, such as [ghost:2.7.1](https://github.com/docker-library/repo-info/blob/98165370ded409e5c100e1d47c94a7b8b68edcd2/repos/ghost/remote/2.7.1-alpine.md)


For your second: don't know, looks like it got skipped and there's just [2.7.1](https://github.com/docker-library/repo-info/blob/98165370ded409e5c100e1d47c94a7b8b68edcd2/repos/ghost/remote/2.7.1-alpine.md) and [2.9](https://github.com/docker-library/repo-info/blob/7b6d9d136a59ff08702c2fa0ab2cc68d14e77a85/repos/ghost/remote/2.9-alpine.md)

**Comment by necevil** [comment]
Hey awesome.
Not sure how I missed those! Closing this one now — 2.9.1 will do the trick!
Thanks @wglambert !
