### ISSUE TITLE
Upgrade to Node v10

### ISSUE THREAD

**Issue by tyler-nguyen** [docker-library/ghost#178]
>Ghost's current recommended Node version is Node v10 LTS

https://docs.ghost.org/faq/node-versions/
It would be nice if the Dockerfile is updated to use Node v10.

**Comment by yosifkit** [comment]
Given that Node 8.x will be switching to "Maintenance LTS" from its current "Active LTS" next month, I say this is a good move (https://nodejs.org/ja/blog/release/v8.9.0/).

Also note that Node 8 will be end of life in December (and probably [version 1](https://docs.ghost.org/faq/major-versions-lts/) of Ghost).

Feel free to make a PR to update the FROM lines, if not, I'll try to get to it this week.
