### ISSUE TITLE
Ghost image based from Node 0.12.x version.

### ISSUE THREAD

**Issue by ssreekanth** [docker-library/ghost#18]
Having a ghost image based from node 0.12-slim, i could have just one version of node image pulled from registry. Saves space on my machine too.

Can we have an official Ghost image based from node:0.12-slim?

**Comment by tianon** [comment]
The current version is based on Node 0.10 because that's what upstream has full support for (https://github.com/tryghost/Ghost#quick-start-install).

> Ghost is also compatible with **Node v0.12** and **io.js v1.2**, but please note that these versions are more likely to run into installation problems. May contain nuts.
>
> ---
>
> Install Node.js.
> 
>     # Node v0.10.x - full support
>     # Node v0.12.x and io.js v1.2 - partial support
>     #
>     # Choose wisely

Since upstream is so carefully timid in their endorsement of using Node 0.12 with Ghost, I'd be wary of doing so here.

**Comment by ssreekanth** [comment]
Closing this issue, as the current ghost docker image is based on node version 4.2.

I would, however, like to see ghost image updated with latest node version (LTS), as and when a newer LTS version of nodejs is released.
