### ISSUE TITLE
Breaking docker images

### ISSUE THREAD

**Issue by etanb** [docker-library/ghost#180]
Hi all,

We’ve been using ghost:1.22.4 for quite some time now and last night it broke. This was due to a Debian dependency on a folder called “jessie-updates” that was removed today as you can see here: https://wiki.debian.org/RecentChanges. Here’s what 1.22.4 seemed to reference: http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages

I see that you all don’t list 1.22.4 to your list on https://hub.docker.com/_/ghost 1. And 1.25.7 doesn’t seem to have a dependency on the “jessie-updates” folder.

Is there a way to be kept appraised of these breaking changes? Of docker image updates in general?

Thank you.

**Comment by tianon** [comment]
See https://github.com/debuerreotype/docker-debian-artifacts/issues/66#issuecomment-476648047 -- this is a temporary glitch that we hope to have resolved before EOD (but that will _only_ go down to the latest `ghost:1` release -- past release tags will never be updated and are not recommended for use).

**Comment by etanb** [comment]
Thanks for the context. What counts as the latest `ghost:1` release? Would 1.22.4 count?

**Comment by yosifkit** [comment]
Only the newest `1` release, so `1.25.7`:
https://github.com/docker-library/ghost/blob/03a0bb9714d69cb2b8c07171792318e41526b890/1/debian/Dockerfile#L26
