### ISSUE TITLE
Too many redirects when using https url

### ISSUE THREAD

**Issue by digitall-it** [docker-library/ghost#182]
When setting ENV variable url to http the site works correctly (even on https) but then all the internal links use http as a protocol. When settings the url to https the browser says there are too many redirects. Is there anything I can try?

Thank you for making Ghost.

**Comment by digitall-it** [comment]
Found out the problem, had to disable the Plesk docker rule redirect, disable the nginx proxy mode and manually create the nginx proxy configuration, letting ghost know that has been redirected.

**Comment by thepra** [comment]
Could you please make a mini guide and preview on the code that you had to make?

**Comment by digitall-it** [comment]
Sure. Create a virtual machine using docker, set it to a fixed port, then create a domain. I suppose you're already to this phase. Disable any docker proxy rules that you've created in Plesk, then in Apache & nginx settings, set under nginx everything off, and under additional nginx directive past this:

```
location ^~ /manifest.json {}

location ^~ /OneSignalSDKUpdaterWorker.js {}

location ^~ /OneSignalSDKWorker.js {}

location ^~ /.well-known/ {}

location / {
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header Host $http_host;
	proxy_set_header X-Forwarded-Proto https;
	proxy_pass http://127.0.0.1:32768;
}
```

first rows are examples that allow to pierce through the proxy and download files on the actual root of the site, for example to enable Let's Encrypt and load OneSignal javascripts. The last location statement allows to emulate the docker proxy rule, replace 32768 with your actual port.
