### ISSUE TITLE
URL's resolving to localhost in production

### ISSUE THREAD

**Issue by Pitu** [docker-library/ghost#184]
Hello everyone, I'm trying to set up ghost using docker and for the most part it works except for a few links here and there. In the footer for example, the links default to localhost:2368 instead of https://my-blog-url. 

Same thing happens on the admin panel, uploading images and favicons don't work since it's pointing to localhost, even though reading blog posts is completely fine. You can see that problem here

![](https://lolisafe.moe/iEx8NFza.PNG)

Same when clicking the `Site` button on the admin panel, it should go to the root domain but instead it appends `/site` to the url ultimately not redirecting you anywhere.

I'm using the following command to run the docker image, also passing the URL env variables required on the docs.

```bash
sudo docker run -d --name some-ghost -p 3001:2368 --mount source=ghost-data,targ
et=/var/lib/ghost/content -e https://my-blog-url -e NODE_ENV=production ghost
```

Am I missing something here?

**Comment by Pitu** [comment]
Same thing happens when trying to upload a picture as a profile picture, it tries to get it from localhost instead of the URL defined on the environment variable passed to docker.

![](https://lolisafe.moe/LbHNdHc8.PNG)

**Comment by djerfy** [comment]
Hi @Pitu,

Test with environment `-e url=https://my-blog-url` and not `-e https://my-blog-url`

**Comment by Pitu** [comment]
@djerfy oh that was such a dumb oversight on my part, I completely forgot to assign the value!
Thanks for the help!
