### ISSUE TITLE
Declaring content/ path as a VOLUME mount point causing problems

### ISSUE THREAD

**Issue by maxcct** [docker-library/ghost#185]
Is this line essential https://github.com/docker-library/ghost/blob/3113ecab0d1edaa9e66ac4c75920114dc16496eb/2/alpine/Dockerfile#L59?

It seems to prevent any modification of the state of that path (see https://github.com/colinmeinke/ghost-storage-adapter-s3/issues/49#issuecomment-488063009).

In my case, I wanted to `mkdir -p /var/lib/ghost/content/adapters/storage`, but this was getting discarded because of the `VOLUME` declaration. I was able to get around this by forking this image and removing that line (as suggested in the comment linked to above), but ideally I'd prefer to use this well-maintained image :)

**Comment by wglambert** [comment]
You could also give the same command as we do in the Dockerfile
https://github.com/docker-library/ghost/blob/d71bcec4c19ae6af38673102ea514c03c8cc80d0/2/debian/Dockerfile#L37

And then change the actual directory to a non-volumized one
https://docs.ghost.org/concepts/config/#paths
