### ISSUE TITLE
Importer fails with sqlite unable to insert default values

### ISSUE THREAD

**Issue by Zagur** [docker-library/ghost#196]
I tried to update the Ghost image to the latest version and it gives me the following error:

> Import failed
> sqlite does not support inserting default values. Specify values explicitly or use the useNullAsDefault config flag. (see docs http://knexjs.org/#Builder-insert).

Docker version: Docker version 18.09.6, build 481bc77

**Comment by wglambert** [comment]
This was an upstream issue https://github.com/TryGhost/Ghost/issues/9587
Looks like it was fixed with https://github.com/stackriot/Ghost/pull/18

Maybe your Ghost version didn't get a backported fix? I would try file an issue with them about it

**Comment by Zagur** [comment]
The docker image for Ghost is the last of the 2.x and was going to upgrade to Ghost 3.1

**Comment by aptalca** [comment]
Ran into the same issue going from 2.37.0 to 3.1.1

**Comment by pascalandy** [comment]
Correct:

> EDIT: Upgrading first to 3.0.0 and then to 3.1.1 seems to work

**Comment by pascalandy** [comment]
We can close this issue.
