### ISSUE TITLE
Why does this not follow the standard Ghost folder structure?

### ISSUE THREAD

**Issue by adam-beck** [docker-library/ghost#20]
I'm very new to Ghost so my assumptions may be way off base, but I have a few questions about this repo that if answered may prove useful in the README for newcomers. 

My first question is why the installation of Ghost is not `/var/www/ghost` which is the recommended installation location according to [this article](http://support.ghost.org/installing-ghost-linux/) from Ghost support docs.

Also, I have a single theme located in a very basic folder structure `~/foo/ghost/content/themes/mytheme` . When I try to map the volume of `/var/lib/ghost` to this folder using the given example: `docker run --name some-ghost -v ~/foo/ghost/:/var/lib/ghost ghost` I would expect my theme to show up in the Settings dashboard. Is this because I don't provide my own `config.js`? Is there a better way to include themes in the blog? When I enter into the running container I notice the structure is more `/var/lib/ghost/themes` which completely bypasses the `content` folder I would expect to see. Am I way off base here?

**Comment by pascalandy** [comment]
I'm having a similar question about adding our own themes. 

It would be nice that have example where the entrepoint.sh loads a theme (not caspter obviously) via git repo (wget or something alike).

**Comment by pascalandy** [comment]
My 5 cents https://github.com/docker-library/ghost/issues/25#issuecomment-247216227

**Comment by tianon** [comment]
As of 1.x, we now use the official Ghost CLI tool for installing Ghost, which sets up a directory structure in a standard way. :+1:
