### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by GregTheGreek** [docker-library/ghost#200]
Does the admin portal come with this ui? I can't seem to locate the port its running on

**Comment by wglambert** [comment]
`/ghost` or `/admin` is the [admin interface](https://ghost.org/docs/concepts/admin/)

**Comment by pascalandy** [comment]
This is a Ghost question, not a question regarding this docker image.

But I can tell you that mydomain.com/ghost is where your admin panel (GUI) is.
You can try Ghost over https://play-with-ghost.com/.

Cheers!

**Comment by acburdine** [comment]
@GregTheGreek the admin runs on the same port that Ghost itself runs on, just on a subpath.

So if you do a vanilla Ghost image run, like so:
```sh
docker run --rm -it -p 2368:2368 ghost:latest
```
your blog homepage will be accessible via http://localhost:2368, and the admin will be accessible via http://localhost:2368/ghost/
