### ISSUE TITLE
Can I SET the database port number as env variable?

### ISSUE THREAD

**Issue by inductor** [docker-library/ghost#201]
Hello, based on the [doc](https://ghost.org/docs/concepts/config/#section-running-ghost-with-config-env-variables), it seems that you do not have support to change port number by default. However, when using a managed DB service it sometimes gives you a different port number other than 3306 for MySQL. Is it possible to make it as an environment variable?

**Comment by wglambert** [comment]
All Ghost configuration parameters (such as `url`) can be specified via environment variables.
https://github.com/docker-library/docs/tree/master/ghost#configuration

You could also use Docker's [port publish](https://docs.docker.com/config/containers/container-networking/#published-ports) option `-p` to remap the port for external connections. For containers on the same network this won't remap the port.

**Comment by inductor** [comment]
I’m asking about the MySQL port not the ghost port...

**Comment by yosifkit** [comment]
`database__connection__port` should work.  (https://ghost.org/docs/concepts/config/#database and https://ghost.org/docs/concepts/config/#running-ghost-with-config-env-variables)
