### ISSUE TITLE
Cannot access Ghost via host IP after setting url ENV variable

### ISSUE THREAD

**Issue by warsix4** [docker-library/ghost#211]
After setting my docker-compose.yml to include
```
environment:
  - url=https://sub.domain.url
```

The site then works at the URL but no longer is able to be accessed using the local IP. Is there a way to allow me to access Ghost from both a local IP and a URL?

**Comment by pascalandy** [comment]
Hi,
Just to manage your expectation you are in the docker project. 
Take a look at: https://forum.ghost.org/

The short answer is yes. You can have a DEV and a PROD config :)

**Comment by warsix4** [comment]
I did not have this issue running outside of a docker container, but that was a long time ago. 

Is this an appropriate place to ask how to have a dev/prod config inside my docker container? I'm assuming it's essentially two containers that share a database?

thanks for prompt response!

**Comment by pascalandy** [comment]
Again, please use Ghost's forum. It's have been asked many time there :)

**Comment by warsix4** [comment]
Not finding anything relative really in their forums, especially since my issue only affects the Docker Container version. If I won't get help here about the Ghost Docker Container then I'll look elsewhere and close the issue.

**Comment by pascalandy** [comment]
Humm: https://forum.ghost.org/search?q=configuration%20file
