### ISSUE TITLE
Mention the admin URL in the install instructions

### ISSUE THREAD

**Issue by jpaugh** [docker-library/ghost#217]
As someone very new to ghost, but familiar with docker and general dev stuff, I easily and quickly got it up and running, but struggled to figure out how to log in. Neither the install guides from ghost.org, nor the [Docker Hub page][hub-page] show how to login to the admin site.

I found this info from a third-party blog post somewhere. Could you include the URL on your Docker Hub page? I also filed this as an issue here: https://github.com/TryGhost/Ghost/issues/11703

[hub-page]: https://hub.docker.com/_/ghost/

**Comment by wglambert** [comment]
Upstream's documentation has it listed in their non-quickstart guide https://ghost.org/docs/install/local/#install-ghost
>Once the install is finished you'll be able to access your new site on `http://localhost:2368` and `http://localhost:2368/ghost` to access Ghost Admin

**Comment by jpaugh** [comment]
That's good to know. I certainly would have found it if I had created my own docker image, then. Obviously, it's not essential, but it does really help someone new to the software.

**Comment by tianon** [comment]
We should probably update our line to match upstream's:

> Then, access it via `http://localhost:3001` or `http://host-ip:3001` in a browser.

into:

> If all goes well, you'll be able to access your new site on `http://localhost:3001` and `http://localhost:3001/ghost` to access Ghost Admin (or `http://host-ip:3001` and `http://host-ip:3001/ghost`, respectively).

**Comment by esentai8** [comment]
> As someone very new to ghost, but familiar with docker and general dev stuff, I easily and quickly got it up and running, but struggled to figure out how to log in. Neither the install guides from ghost.org, nor the [Docker Hub page](https://hub.docker.com/_/ghost/) show how to login to the admin site.
> 
> I found this info from a third-party blog post somewhere. Could you include the URL on your Docker Hub page? I also filed this as an issue here: [TryGhost/Ghost#11703](https://github.com/TryGhost/Ghost/issues/11703)

Could you please advise where exactly what the admin URL is? I downloaded the image and ran container but am struggling to get to the admin settings. Thank you in advance!

**Comment by pascalandy** [comment]
see https://github.com/docker-library/ghost/issues/217#issuecomment-606903492

**Comment by gringogriot** [comment]
It is absolutely ridiculous that this is still a problem. I spent more time googling, trying to find the answer to this most basic question, than I did actually setting up the container. Tons of information all over the internet about how to configure Ghost, but absolutely nowhere (until this feature request) actually specifying how to access any of it. Can this info at least live prominently somewhere in the Ghost docs?

**Comment by LaurentGoderre** [comment]
@gringogriot could you open a PR to add it to this file? https://github.com/docker-library/docs/blob/master/ghost/content.md

**Comment by audas** [comment]
I have spent a very long time trying to work out how to access the admin interface. As someone with decades of experience (and multiple servers running every possible docker container imaginable) - this was an amazing experience.

https://ghost.org/docs/config/

Clearly there is a very strong bias towards CLI - I get that. But just putting such basic info in the docs is not hard - almost seems deliberate at this point.
