### ISSUE TITLE
Developing Themes 

### ISSUE THREAD

**Issue by adam-beck** [docker-library/ghost#22]
Is there a way to develop themes and use this Dockerfile? I've tried mounting a volume `$PWD/my_theme/:/usr/src/ghost/content/themes/my_theme` and the directory is created in `/var/lib/ghost/themes` but the files are not copied over. I'm not quite sure why as the `entrypoint.sh` copies all directories and I'm assuming the files with it as well. Has anybody had experience with this or does the `entrypoint.sh` need to be updated to allow mounted volumes to be recursed over for files inside of directories?

I've also tried directly mounting to `/var/lib/ghost/themes` but then the `casper` theme is not located there. This might be a separate issue, but I can't figure out why it would disappear. Wouldn't the `entrypoint.sh` still copy the files from `/usr/src/ghost`?

**Comment by knickers** [comment]
I'm also seeing this same thing in some simple testing.
```
$ mkdir my-theme
$ touch my-theme/test.txt
$ docker run -d --name ghost-test -v my-theme:/usr/src/ghost/content/themes/my-theme ghost
$ docker exec -it ghost-test bash
$ ls content/themes/
casper  my-theme
$ ls content/themes/my-theme/
$ 
```
Directory is empty.
Are you still having this issue @adam-beck?

**Comment by lwis** [comment]
Mount '/var/lib/ghost' instead, under that volume you'll find 'themes'.

**Comment by adam-beck** [comment]
so @knickers I'm thinking the extraction doesn't complete because of user permissions. Unfortunately, I don't have enough experience to say for sure or even how to go about fixing it. I did figure out why the casper theme disappears when mounting directly to `/var/lib/ghost/themes`. It's because there is  string check in the `entrypoint.sh` that checks if there are values in `/var/lib/ghost/$DIRECTORY` then don't copy it from `/usr/src/ghost/content/$DIRECTORY`

@lwis I could do that but it would require that all necessary files are in the volume that I mount. What I would really like to accomplish is mounting the 1 theme I'm currently developing. See above comment for why I can't just mount to `/var/lib/ghost/themes/$MY_THEME`

**Comment by tianon** [comment]
@adam-beck are you using boot2docker? (are you on Windows or OSX?)

**Comment by adam-beck** [comment]
@tianon no I'm not using boot2docker. I'm on Ubuntu 15.10 now (possibly 15.04 when I last worked on this)

**Comment by paislee** [comment]
I did some work on theme development with Docker, this seemed like a good place to share http://paislee.io/how-to-develop-ghost-themes-wth-docker/.
