### ISSUE TITLE
upon adding new users im getting this error when sending email 

### ISSUE THREAD

**Issue by soydepr** [docker-library/ghost#222]
Error sending email! Error sending email: Failed to send email. Reason: Can't send mail - all recipients were rejected. Please check your email settings and resend the invitation.

someone point which settings are these

**Comment by pascalandy** [comment]
Hi,
This is not related to this docker image. But let me try to help :-p

This is part of the config file: https://ghost.org/docs/concepts/config/#mail
Ghost create one by default (without mail configs).

**Comment by soydepr** [comment]
ty
