### ISSUE TITLE
Failed migration from 3.21 to 3.22

### ISSUE THREAD

**Issue by distolma** [docker-library/ghost#227]
Hi, my app can't startup after upgrade from v3.21.1 to v3.22

> ghost    | [2020-07-02 13:57:18] INFO Deleting ghost_head
> ghost    | [2020-07-02 13:57:18] INFO Updating ghost_foot with value from codeinjection_foot
> ghost    | [2020-07-02 13:57:18] INFO Deleting ghost_foot
> ghost    | [2020-07-02 13:57:18] INFO Updating brand with value from accent_color
> ghost    | [2020-07-02 13:57:18] INFO Deleting brand
> ghost    | [2020-07-02 13:57:18] INFO Adding force_i18n, permalinks, and members_session_secret to "settings" table.
> ghost    | [2020-07-02 13:57:18] ERROR Cannot read property 'toString' of undefined
> ghost    |
> ghost    | Cannot read property 'toString' of undefined
> ghost    |
> ghost    | {"config":{"transaction":true},"name":"05-migrate-members-subscription-settings.js"}
> ghost    | "Error occurred while executing the following migration: 05-migrate-members-subscription-settings.js"
> ghost    |
> ghost    | Error ID:
> ghost    |     300
> ghost    |
> ghost    | ----------------------------------------
> ghost    |
> ghost    | MigrationScriptError: Cannot read property 'toString' of undefined
> ghost    |     at MigrationScriptError.KnexMigrateError (/var/lib/ghost/versions/3.22.1/node_modules/knex-migrator/lib/errors.js:7:26)
> ghost    |     at new MigrationScriptError (/var/lib/ghost/versions/3.22.1/node_modules/knex-migrator/lib/errors.js:25:26)
> ghost    |     at /var/lib/ghost/versions/3.22.1/node_modules/knex-migrator/lib/index.js:1055:19
> ghost    |
> ghost    | TypeError: Cannot read property 'toString' of undefined
> ghost    |     at Object.up (/var/lib/ghost/versions/3.22.1/core/server/data/migrations/versions/3.22/05-migrate-members-subscription-settings.js:72:43)
> ghost    |
> mysql    | 2020-07-02T13:57:18.549453Z 93 [Note] Aborted connection 93 to db: 'db' user: 'blog-user' host: '172.30.0.3' (Got an error reading communication packets)
> ghost exited with code 255

**Comment by yosifkit** [comment]
I don' think this is a problem specific to the docker image but is an upstream bug. It's failing in the same file as https://github.com/TryGhost/Ghost/issues/11993.

**Comment by distolma** [comment]
Ok, I see. Thanks
