### ISSUE TITLE
Error message with Docker image in Plesk

### ISSUE THREAD

**Issue by temabu** [docker-library/ghost#233]
Downloading 3.33+ versions of Docker Ghost image I get the following message on Ubuntu 16.04 LTS and Plesk Web edition:

**no matching manifest for linux/amd64 in the manifest list entries**

3.32.2 and 3.32.2-alpine is ok

**Comment by wglambert** [comment]
I'm not able to reproduce, might have been related to an update being pushed when you were trying to pull it https://github.com/docker-library/official-images/pull/8771

```console
$ docker pull ghost:3.33
3.33: Pulling from library/ghost
d121f8d1c412: Pull complete 
3a54a24e4e59: Pull complete 
8aa65a634fc0: Pull complete 
7634d710af87: Pull complete 
ec150ee2ad17: Pull complete 
8d63bf0b1e87: Pull complete 
2f2b08fee21d: Pull complete 
2c40dde45872: Pull complete 
41eca2adb4a9: Pull complete 
Digest: sha256:cac082c07714e7e50baae3f56bffbe0d2b2d423aab2234c34cb579f9651cca74
Status: Downloaded newer image for ghost:3.33
docker.io/library/ghost:3.33
```

**Comment by temabu** [comment]
Possibly, as it now appears fixed.

**Comment by wglambert** [comment]
Cool, going to close then as this appears resolved
