### ISSUE TITLE
How to pass Stripe-CLI's WEBHOOK_SECRET to Dockerized ghost instance?

### ISSUE THREAD

**Issue by robhutters** [docker-library/ghost#238]
Hi,

A friend has graciously offered to host my ghost instance on his VPS, but his one requirement is that I dockerize it.

The only thing standing in my way right now is that Stripe CLI (dockerized) won't play nice with Ghost (dockerized). I'm unable to pass the WEBHOOK_SECRET that Stripe's CLI provides to the Dockerized Ghost instance.

Here's my setup:

- MariaDB / Ghost / NGINX managed by docker-compose.yml : https://hastebin.com/asiqinuron.http 
- Stripe CLI running in a separate container connected to the same network as Ghost.

All I need to do is make Ghost aware of the `whsec` key. How do I do this?

The [docs](https://ghost.org/docs/members/webhooks/) say that the secret needs to be given to ghost on startup. 

The expected output should be this:

```
[2020-11-03 16:16:48] INFO Ghost boot 22.685s
[2020-11-03 16:16:50] WARN Skipping Stripe webhook creation and validation, using WEBHOOK_SECRET environment variable
```

But this is what I get from the Dockerized version no matter what I try (excerpt)

```
[2020-11-03 16:48:44] INFO Creating Stripe webhook with url: http://localhost:2368/members/webhooks/stripe/, version: 2019-09-09, events: checkout.session.completed, customer.subscription.deleted, customer.subscription.updated, customer.subscription.created, invoice.payment_succeeded, invoice.payment_failed

[2020-11-03 16:48:44] ERROR Failed to create Stripe webhook. For local development please see https://ghost.org/docs/members/webhooks/#stripe-webhooks
```

Notice that the docker-compose.yml file contains this line: `members__stripe__webhook__secret: ${WEBHOOK_SECRET}`

Does such an option exist at all? I've been guessing based on what I found in Ghost's source code. The Ghost docs make no mention of this config option so it probably doesn't exist. 

I even tried passing it by adding it to the package.json `npm start` line, to no avail. It was a Hail Mary on my part.

Thank you for your time.

**Comment by tianon** [comment]
Instead of:

```yaml
members__stripe__webhook__secret: ${WEBHOOK_SECRET}
```

I think you just want:

```yaml
WEBHOOK_SECRET: ${WEBHOOK_SECRET}
```

(According to the linked documentation at https://ghost.org/docs/members/webhooks/#stripe-webhooks)

**Comment by robhutters** [comment]
I thought I'd already tried that ... because it seemed so obvious ... 

Maybe I did try it, but with two underscores? 

Unbelievable. 

It worked.

Thanks a lot.
