### ISSUE TITLE
Links defaulting to localhost

### ISSUE THREAD

**Issue by un-fuf-a-doo** [docker-library/ghost#243]
Hi ... 

I'm trying to get the docker image setup and everything appears to work, but several default links in the base site seem to be hard coded to localhost. For example from the /ghost/ admin page, when I click on View Site, the iframe tries to load localhost:2368 instead of my actual IP or Hostname, which results in a localhost refused connection error.

Where can I change this so the default site/server uses my actual IP or Hostname?

Thanks.

OS:  Ubuntu 20.04
DOCKER:  Latest
Ghost:  Latest

**Comment by acburdine** [comment]
@un-fuf-a-doo Ghost by default uses localhost:2368 as the URL. If you wish to change that, you'll need to pass in an environment variable called `url`, with the value that you wish to use.

For example, if you wanted your URL to be https://example.com, you'd start your docker container with `-e url=https://example.com`.

For additional configuration options please see [the docs](https://ghost.org/docs/config/#configuration-options) 😄

**Comment by un-fuf-a-doo** [comment]
Awesome.  That is what I was looking for.

Thank-you!
