### ISSUE TITLE
ghost 3.42.0 : no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by euri10** [docker-library/ghost#247]
greetings, I get this error trying to pull latest 3.42.0

```
❯ dcupd --build
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Pulling ghost (ghost:3.42.0)...
3.42.0: Pulling from library/ghost
ERROR: no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by tianon** [comment]
Indeed, unfortunately the official images amd64 build server stopped responding and we're still trying to investigate 😱

(Closing this in favor of https://github.com/docker-library/official-images/issues/9749 😬❤️)
