### ISSUE TITLE
Disabling Ghost service router's ability to return 'Moved Permenently' response code when `url` has `https` in it.

### ISSUE THREAD

**Issue by pavelexpertov** [docker-library/ghost#251]
I use a ghost docker image behind an nginx web server.

The web server acts as a reverse proxy server and thus it already does HTTPS connections.

The ghost container is running behind it. The server just routes it to the ghost instance.

The problem is that when `url` environment variable is set with a URL that starts with `https://`, requests that get passed to the instance gets a response of 301 and the nginx doesn't return anything. Thus a site gets broken.
Furthermore, if I place a normal HTTP protocol in the URL, the instance inserts the normal protocol into all links. I had to make nginx to redirect them to https but it makes certain features of dashboard unworkable. 
Is there a way to tell the instance to accept requests without sending the 301 code?

Thanks

**Comment by acburdine** [comment]
@pavelexpertov do you have the following line in your Nginx config?

```
proxy_set_header X-Forwarded-Proto $scheme;
```

if you have that header set, Ghost shouldn't return a 301. If you'd like, you can look at the nginx config that [Ghost-CLI installs](https://github.com/TryGhost/Ghost-CLI/blob/master/extensions/nginx/templates/nginx-ssl.conf#L13-L16) by default, in case you're missing any additional lines 😄

**Comment by pavelexpertov** [comment]
@acburdine thanks for the suggestion!
It works good when I copied necessary proxy_set_header settings in the `location`.
