### ISSUE TITLE
SQLite v5.0.2 might cause issue to Send bulk email to members

### ISSUE THREAD

**Issue by pascalandy** [docker-library/ghost#261]
## Context

A client of mine is unable to send bulk email. He have only 40 emails at this point.)

We [opened a bug](https://forum.ghost.org/t/unable-to-send-bulk-email-with-mailgun/22467/6) on the Ghost forum.

Kevin (Ghost core dev) said:

> SQLITE_ERROR: too many SQL variables is the error.
> I’d suggest upgrading to a newer version of SQLite or switching to using MySQL which is the recommended database for production sites.

## My investigation
[I can see](https://pkgs.org/download/sqlite3) that the latest SQLite version is 3.35.5

I wonder which version we use in this Docker image. From the log of the Github Actions CI, I found that we force to install Sqlite 5.0.2. So I'm confused !

Any reason we don't use SQLite v3.35.5 ?

![Screen Shot 2021-05-06 at 11 39 50 AM](https://user-images.githubusercontent.com/6694151/117329359-93861c80-ae62-11eb-9bd3-98d31078ad63.jpg)

![Screen Shot 2021-05-06 at 11 39 57 AM](https://user-images.githubusercontent.com/6694151/117329387-9a149400-ae62-11eb-91f1-efea4573f8bb.jpg)

Thanks!
Pascal

**Comment by tianon** [comment]
We install the version of the `sqlite3` Node.js package that the Ghost project includes in its "optionalDependencies" (that's what that bit of code you've highlighted is doing).

Looking at https://www.npmjs.com/package/sqlite3, the 5.0.2 getting installed is the latest available at this time.

The underlying version of SQLite 3 that it bundles appears to be 3.32.3 (if their documentation is up-to-date), which is newer than the version that's currently available in Debian Stable (https://packages.debian.org/buster/sqlite3; 3.27.2), so I don't think there's much for us to do here.

(I guess https://github.com/mapbox/node-sqlite3/issues/1453 is likely relevant.)

**Comment by pascalandy** [comment]
Thank for your insight on this ! As we build the image on `alpine`, do you know where to find the SQLite package supported by alpine ?

> The underlying version of SQLite 3 that it bundles appears to be 3.32.3 (if their documentation is up-to-date), which is newer than the version that's currently available in Debian Stable (https://packages.debian.org/buster/sqlite3; 3.27.2), so I don't think there's much for us to do here.

**Comment by tianon** [comment]
Still slightly behind what's bundled: https://pkgs.alpinelinux.org/packages?name=sqlite&branch=v3.12 (3.32.1)

**Comment by pascalandy** [comment]
Thank you. I'm our case, we use Node 14 and alpine 3.13. https://pkgs.alpinelinux.org/packages?name=sqlite&branch=v3.13

- Debian SQLite 3.27.2
- On alpine 3.12 : SQLite 3.32.1-r0
- On alpine 3.13 : SQLite 3.34.1-r0

I'll try to rebuild on 3.12. But this is still a nasty bug.

**Comment by tianon** [comment]
It looks like https://github.com/TryGhost/node-sqlite3/commit/9a1b172048125dd8e65935ab771d8483ebcfd744 got us 3.38.4 :+1:
