### ISSUE TITLE
Unable to run ghost.js via Docker. Keep on getting error.

### ISSUE THREAD

**Issue by ewliang** [docker-library/ghost#262]
![image](https://user-images.githubusercontent.com/6957377/123471515-c15a2880-d5aa-11eb-8f2d-3f21a2e53225.png)
``` 
site2:
    #build: ./site2
    #image: ghost:latest
    image: ghost:4.8.3
    container_name: site2
    restart: always
    ports:
      - 127.0.0.1:2368:2368
    volumes:
      - ./site2:/var/lib/ghost/content
      - ./site2/config.production.json:/var/lib/ghost/config.production.json
    networks:
      - proxy
```

```
NOTE: I also tried my url as both ... blog and blog/ but neither worked. Back when I was running ghostjs on a old version, i had it as blog (without a / at the end) and it worked. This file has not been changed.
{
  "url": "https://www.eric-liang.com/blog",
  "server": {
    "port": 2368,
    "host": "0.0.0.0"
  },
  "database": {
    "client": "sqlite3",
    "connection": {
      "filename": "/var/lib/ghost/content/data/ghost.db"
    }
  },
  "mail": {
    "transport": "Direct"
  },
  "logging": {
    "transports": [
      "file",
      "stdout"
    ]
  },
  "process": "systemd",
  "paths": {
    "contentPath": "/var/lib/ghost/content"
  }
}

```
I tried 4.7.x series, 4.8.3. No luck.
I tried uncommenting my build line which also produces same issue.
The container just crashes after 5 seconds.
Not sure what I'm doing wrong. 
It used to work just fine in a super old version of Ghostjs.
Note: I even deleted my database just to see if it can run via stock/fresh off the image, but no luck. 
Any ideas?

**Comment by pascalandy** [comment]
Please share your config.production.json
Here is a [template I maintain](https://github.com/firepress-org/ghostfire/blob/master/config.production.json).

**Comment by ewliang** [comment]
@pascalandy Shared. I updated the post to include my config.production.json

**Comment by tianon** [comment]
FWIW, your configuration file looks like it is almost the default verbatim, so you could ditch the whole file and just set `url=https://www.eric-liang.com/blog` as an environment variable (not sure whether that would do anything for the error you're running into, though).

**Comment by pascalandy** [comment]
Yeah make sense. In your compose-file above your should define the env as well.
Because your are using /blog/, you know you need a reserve-proxy.

**Comment by ewliang** [comment]
@tianon The config file I have is the one I've been using when my ghostjs was running on 1.xx version series. When I do deploy, I just do "sudo docker-compose up -d site2". Since it's just a simple website, I just ultimately hardcoded the values in since there's really nothing noteworthy of loss and I don't plan to re-use it anywhere else since it is a personal site. 

@pascalandy Yeah, the entire site with all the rest of the containers that make up the entire thing goes through a nginx reverse proxy.  Also, what env variable are you referring to?

**Comment by acburdine** [comment]
> The config file I have is the one I've been using when my ghostjs was running on 1.xx version series.

@ewliang I have an idea as to what's going on here, but can you first clarify something? when you say "since running on 1.x" do you mean that you updated from 1.x directly to 4.x? or you've just kept the same config file since then?

the reason I ask is the error you're getting _should_ have automatically been fixed when upgrading from Ghost 1.x to Ghost 2.x (the `content/settings/routes.yaml` file was updated and `permalink: '{globals.permalinks}'` was replaced with `permalink: /{slug}/`. Applying that change yourself _should_ fix the issue, but if you did upgrade from 1.x straight to 4.x, then there might be other issues that come up.

**Comment by ewliang** [comment]
> > The config file I have is the one I've been using when my ghostjs was running on 1.xx version series.
> 
> @ewliang I have an idea as to what's going on here, but can you first clarify something? when you say "since running on 1.x" do you mean that you updated from 1.x directly to 4.x? or you've just kept the same config file since then?
> 
> the reason I ask is the error you're getting _should_ have automatically been fixed when upgrading from Ghost 1.x to Ghost 2.x (the `content/settings/routes.yaml` file was updated and `permalink: '{globals.permalinks}'` was replaced with `permalink: /{slug}/`. Applying that change yourself _should_ fix the issue, but if you did upgrade from 1.x straight to 4.x, then there might be other issues that come up.

Currently I've been trying to just simply get version 4.x up and running without any files in the /data/ folder. Only content that's being ported over are my images in the images folder. That's all. So no existing .json. No existing .db. 

As for the config file that I pasted when you first asked me for it, that is the exact file I used since 1.x and I've never modified it since. 

In other words, the setup I have is pretty much close to stock default (other than my production config file and whatever I shared for docker compose and in this reply :) )

I also did a restart on my nginx in hopes of it being just a cache issue, but sadly it's not.

I'm also using a simple custom theme (which ran fine when I installed ghostjs locally on my Windows 10 laptop), so I doubt it would be the theme... There's also the old casper theme in there.

**Comment by acburdine** [comment]
@ewliang I wasn't talking about files in the data folder 😄  inside your mounted `content` directory there should be a few different folders, among them `data`, `images`, `themes`, and the one that's causing the issue - `settings`.

Inside that `settings` folder there should be a `routes.yaml` file - would you mind pasting that here?

**Comment by ewliang** [comment]
> @ewliang the routes.yaml file I mentioned isn't in the data folder 😄 inside your mounted `content` directory there should be a few different folders, among them `data`, `images`, `themes`, and the one that's causing the issue - `settings`.
> 
> Inside that `settings` folder there should be a `routes.yaml` file - would you mind pasting that here?

LMAO I never knew there was a file in there. (Never accessed it before)
Maybe that is the problem....

```
routes:

collections:
  /:
    permalink: '{globals.permalinks}' # special 1.0 compatibility setting. See the docs for details.
    template:
      - index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```

**Comment by acburdine** [comment]
yup - my guess is due to the way the docker volume is mounted, that file never got updated between Ghost versions 😅 

if you update that file to match this one: https://github.com/TryGhost/Ghost/blob/main/core/frontend/services/settings/default-routes.yaml I _believe_ you should be able to get Ghost starting again

**Comment by ewliang** [comment]
> yup - my guess is due to the way the docker volume is mounted, that file never got updated between Ghost versions 😅
> 
> if you update that file to match this one: https://github.com/TryGhost/Ghost/blob/main/core/frontend/services/settings/default-routes.yaml I _believe_ you should be able to get Ghost starting again

@acburdine That solved the crashing issue; however, when I visit the actual site in the browser, this is what the logs show me:

![image](https://user-images.githubusercontent.com/6957377/123494049-5e30bc00-d5d3-11eb-9baa-92bc7550cc40.png)

Browser shows this. I also tried Ctrl F5 and private browser but no luck. Site doesn't crash. It just infinitely redirects for some reason.
![image](https://user-images.githubusercontent.com/6957377/123494110-96d09580-d5d3-11eb-9f51-9b422ff2cea9.png)

**Comment by acburdine** [comment]
@ewliang can you share your nginx configuration (at least the part that corresponds to the `/blog/` subpath)? Most likely the nginx config is missing a `proxy_redirect: off;` setting, which could cause that infinite redirect issue.

**Comment by ewliang** [comment]
> @ewliang can you share your nginx configuration (at least the part that corresponds to the `/blog/` subpath)? Most likely the nginx config is missing a `proxy_redirect: off;` setting, which could cause that infinite redirect issue.

@acburdine Unchanged since day 1 of deployment (same goes for the rest of the nginx conf that's not pasted).

```
    location ^~/blog {
        # This connects to your blog container
        #Deployment
        proxy_pass http://site2;
        proxy_redirect     off;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Host $server_name;
    }
```

**Comment by acburdine** [comment]
hmm....ok - can you try adding the following line to that block?

```nginx
proxy_set_header X-Forwarded-Proto $scheme;
```

**Comment by ewliang** [comment]
> hmm....ok - can you try adding the following line to that block?
> 
> ```nginx
> proxy_set_header X-Forwarded-Proto $scheme;
> ```

@acburdine Bam! That did the trick! Thank you so much for your help! 🥳
