### ISSUE TITLE
Instantly crashes when trying to specifically upload pictures

### ISSUE THREAD

**Issue by themaster567** [docker-library/ghost#267]
I'm running the latest version of the container on Debian 10. Everything works perfectly, I can even upload a routes.yaml file without issue(proving it's not ALL uploads that are a problem), but if I try to upload an image for an article, the site banner, a profile banner, or even an avatar, a red message appears at the top saying "request was rejected due to server error" and the container instantly crashes and restarts. [Here are the relevant logs.](https://pastebin.com/VkVLpVFW)

**Comment by siberkolosis** [comment]
same to me...
https://forum.cloudron.io/topic/5015/ghost-4-4-0-cant-upload-image-for-icon-and-logo/14

**Comment by kz26** [comment]
Same issue happens with the 3.42.8-alpine Docker image. Switching to the regular 3.42.8 image fixes the problem.
