### ISSUE TITLE
v4.22.0 is missing on docker hub

### ISSUE THREAD

**Issue by foolioo** [docker-library/ghost#270]
the [master branch holds v4.22.0](https://github.com/docker-library/ghost/commit/742d137a05e3e4048316d45dafb3b7afe54307cf) but this version is [not available in docker hub images](https://hub.docker.com/_/ghost?tab=tags&page=1&name=4.22).

when is it going to be available on docker hub?
the same question for each new release of ghost, how long does it take to reach docker hub once update happens in this repository?

**Comment by pascalandy** [comment]
It's usually avail. within 12-24 hours. 
In this case, I feel there are issue regarding multi-arch builds. Just my 2 satoshis.

**Comment by foolioo** [comment]
the readme indicates that both builds passes and this made my wonder why it is still not available on docker hub...

![image](https://user-images.githubusercontent.com/28758375/140806237-d00b29b0-a6b4-42c5-a582-d8ab2d685891.png)

**Comment by yosifkit** [comment]
https://github.com/docker-library/ghost/tree/742d137a05e3e4048316d45dafb3b7afe54307cf#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

So, they'll exist after https://github.com/docker-library/official-images/pull/11253 is merged and built.
