### ISSUE TITLE
Consider adding a user

### ISSUE THREAD

**Issue by enjunear** [docker-library/ghost#278]
Per [dockerfile docs](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user), consider adding a user to the container and running as that user, instead of running as root.

**Comment by tianon** [comment]
Since we're `FROM node`, we inherit the `node` user it creates, which we step down to after adjusting permissions:

https://github.com/docker-library/ghost/blob/f9e21738c57f92c845497d9ea27f6f7c10b1cf9c/4/debian/docker-entrypoint.sh#L4-L8

**Comment by enjunear** [comment]
Indeed

**Comment by tianon** [comment]
The `chown` that's happening in the entrypoint script is happening on the user-provided volume, not on the contents of the image (we *do* in fact do as much `chown`ing in the `Dockerfile` as we can :sweat_smile:).

**Comment by rabume** [comment]
I would like to use the docker image for local theme development, but my host user has not the uid / gid 1000. 
Container rewrites all the permissions which makes it impossible to work on my theme. Here is an example of a ghost theme with a containerized dev env: https://github.com/eddiesigner/liebling/wiki/Theme-development-with-Docker

If we could define the user from the outside this would make things a lot easier.

**Comment by yosifkit** [comment]
> If we could define the user from the outside this would make things a lot easier.

Use the `--user` flag on docker run with the user and group ids that you need. The image is designed such that any value but root *should* work (https://github.com/docker-library/ghost/pull/54).

**Comment by rabume** [comment]
Thanks for the response. I tried this flag before already but still dace the same issue. Binded host files / folder the permission gets set to the root user. Theonly thing that made it semi work was a custom docker image in wich I set the user bur then I get the issue that ghost can not read ceratin files anymore. (e.g casper theme)
