### ISSUE TITLE
Cannot restart NPM

### ISSUE THREAD

**Issue by calvinchristopher** [docker-library/ghost#28]
after making changes to theme or config.js, a reload of NPM is needed. Restarting the container does not apply the needed changes, and restarting NPM doesn't work either.

<pre>
root@61583f8d0b57:/usr/src/ghost# npm restart
npm info it worked if it ends with ok
npm info using npm@2.14.12
npm info using node@v4.2.4
npm info prerestart ghost@0.7.5
npm info prestop ghost@0.7.5
npm info stop ghost@0.7.5
npm info poststop ghost@0.7.5
npm info restart ghost@0.7.5
npm info prestart ghost@0.7.5
npm info start ghost@0.7.5

> ghost@0.7.5 start /usr/src/ghost
> node index

using this config!
GHOST_CONTENT: /var/lib/ghost
GHOST_SOURCE: /usr/src/ghost
ERROR: Cannot find the configuration for the current NODE_ENV: undefined

Ensure your config.js has a section for the current NODE_ENV value and is formatted properly.

npm info ghost@0.7.5 Failed to exec start script
npm ERR! Linux 3.19.0-43-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "restart"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! ghost@0.7.5 start: `node index`
npm ERR! Exit status 232
npm ERR! 
npm ERR! Failed at the ghost@0.7.5 start script 'node index'.
npm ERR! This is most likely a problem with the ghost package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index
npm ERR! You can get their info via:
npm ERR!     npm owner ls ghost
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/ghost/npm-debug.log

**Comment by vardestiny** [comment]
Same situation for me. Is there any official way to fix it? Or any other work around for this issue

**Comment by adam-beck** [comment]
Is your config file valid? Could you share it here with any sensitive information removed? I'm curious as to why your NODE_ENV is being set to `undefined`. That is where I think the problem is stemming from. @vardestiny are you seeing the exact same error output?

**Comment by chanoch** [comment]
I have the same problem. Could it be the Dockerfile rather than the config file? here is my config file:

````javascript
// # Ghost Configuration
// Setup your Ghost install for various [environments](http://support.ghost.org/config/#about-environments).

// Ghost runs in `development` mode by default. Full documentation can be found at http://support.ghost.org/config/

var path = require('path'),
    config;

config = {
    // ### Production
    // When running Ghost in the wild, use the production environment.
    // Configure your URL and mail settings here
    production: {
        url: 'http://acme.io',
        mail: {},
        // Example mail config
        // Visit http://support.ghost.org/mail for instructions
        // ```
        //  mail: {
        //      transport: 'SMTP',
        //      options: {
        //          service: 'Mailgun',
        //          auth: {
        //              user: '', // mailgun username
        //              pass: ''  // mailgun password
        //          }
        //      }
        //  },
        // ```

        database: {
            client: 'sqlite3',
            connection: {
                filename: path.join(__dirname, '/content/data/ghost.db')
            },
            debug: false
        },

        server: {
            host: '0.0.0.0', 
            port: '2368'
        }
    }
};

module.exports = config;
````

**Comment by shotah** [comment]
Having the same issue, I'm trying to start it with the NODE_ENV set to production and it isn't working. `sudo docker run -d -v /home/user/ghost:/var/lib/ghost -it --name ghost -e NODE_ENV=production ghost`

**Comment by calvinchristopher** [comment]
developer isn't paying attention to our plight, closing issue
