### ISSUE TITLE
4.32.3 4.32.2 fails to boot with Assertion `(0) == (uv_gettimeofday(&tv))' failed

### ISSUE THREAD

**Issue by philmale** [docker-library/ghost#283]
Docker container failing to start up on arm7l Raspbian GNU/Linux 10 (buster) with versions 4.32.3 and 4.32.2 with the following assertion failure:

`Node.js[1]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion '(0) == (uv_gettimeofday(&tv))' failed.`

Version 4.32.1 works fine.

**Comment by tianon** [comment]
It's possible this is related to (semi-)recent seccomp issues/changes -- what's the version of Docker and libseccomp on the host? (At least Docker 20.10.8+ and libseccomp 2.4.2+?)

(See also https://github.com/moby/moby/issues/40734)

**Comment by philmale** [comment]
spot on - good spot - docker at 20.10.12 but seccomp at 2.3.3-4 on this host - tried on another identical host with sec comp at 2.5.3-2 and latest image works.
