### ISSUE TITLE
Image does not listen on IPv6

### ISSUE THREAD

**Issue by Niduroki** [docker-library/ghost#291]
This image does not listen on IPv6 connections:

```
[root@Alice chris]# docker pull ghost
Using default tag: latest
latest: Pulling from library/ghost
[…]
[root@Alice chris]# docker run --name ghost ghost
[2022-02-28 15:02:34] INFO Ghost is running in production...
[2022-02-28 15:02:34] INFO Your site is now available on http://localhost:2368/
[2022-02-28 15:02:34] INFO Ctrl+C to shut down
[2022-02-28 15:02:34] INFO Ghost server started in 0.203s
[2022-02-28 15:02:34] WARN Database state requires initialisation.
[…]
[2022-02-28 15:02:38] INFO Ghost URL Service Ready in 3.992s
```

Another terminal 

```
[root@Alice chris]# docker exec -it ghost bash
root@d01c4b5a351a:/var/lib/ghost# apt-get update
[…]
root@d01c4b5a351a:/var/lib/ghost# apt-get install curl
[…]
root@d01c4b5a351a:/var/lib/ghost# curl -4 localhost:2368
<!DOCTYPE html>
<html lang="en">
[…]
root@d01c4b5a351a:/var/lib/ghost# curl -6 localhost:2368
curl: (7) Failed to connect to ::1 port 2368: Connection refused
```

Causes annoyances, when working with Dual Stack (e.g. reverse-proxy resolves to IPv6 first, doesn't work, tries IPv4 afterwards, works - spams the logs with bogus `502: Connection refused` errors, though), could mean trouble, when using IPv6 only (if docker allows such a thing?).

I would wage a guess, that adding `--ip [::]` to [debian/Dockerfile:57](https://github.com/docker-library/ghost/blob/master/4/debian/Dockerfile#L57) and [alpine/Dockerfile:33](https://github.com/docker-library/ghost/blob/master/4/alpine/Dockerfile#L33) would fix this, I'm not too good with node, though, so might not work.

----

When testing: Do make sure, that your Docker Daemon is actually using IPv6.
If you get

```
root@d01c4b5a351a:/var/lib/ghost# curl -6 localhost:2368
curl: (7) Couldn't connect to server
```
it's not configured properly.

Here's an example `/etc/docker/daemon.json`:
```
{
          "ipv6": true,
          "fixed-cidr-v6": "fd00:dead:beef::/48"
}
```
(don't forget to restart docker, after changing `daemon.json`)

**Comment by tianon** [comment]
In my testing, replacing `'0.0.0.0'` with just `'::'` seems to still work for non-IPv6 enabled uses (which was a concern I had with switching, but it appears Node is smart enough to adjust).

The resulting configuration this generates is thus:

```json
...
  "server": {
    "port": 2368,
    "host": "::"
  },
...
```

I _think_ this is probably reasonable/safe?

A simpler way to test IPv6 without enabling it on the whole daemon is `--sysctl net.ipv6.conf.all.disable_ipv6=0` on the container (which will then generate the appropriate link-local addresses).
