### ISSUE TITLE
Advance notice about upcoming changes to database support

### ISSUE THREAD

**Issue by daniellockyer** [docker-library/ghost#294]
Hey all! 👋🏻 I work on the Ghost core team and we're starting to make preparations for Ghost 5.0, which we hope to ship in a few months.

We're making some changes to the databases we support in development and production. We want to simplify the list of databases that Ghost must maintain compatibility with, so we can double down on performance optimizations and correctness of the migrations we ship weekly.

Our plan is, starting with Ghost 5.0:

| Enviroment | Supported Database(s) |
| ---- | ----- |
| development | MySQL 8 and SQLite |
| production | MySQL 8 |

Note: MySQL 5.7 is NOT supported in Ghost 5.0.

I'm opening this issue to start the conversation with the repo maintainers about the changes we're making, as it looks like there will need to be some updates to the Docker images and docs when the time comes.

Over the coming weeks and months we'll be shipping more docs, updates and tooling to help the migration to a supported database 🙂

**Comment by tianon** [comment]
Nice, thanks for the heads up!  As far as I can tell, the only thing that will probably need to actually change is the example `stack.yml`/`docker-compose.yml` that currently refers to `mysql:5.7`. :sweat_smile:

If 4.x already supports MySQL 8, then we don't even need to wait for Ghost 5.x before we update that. :smile:

**Comment by daniellockyer** [comment]
@tianon It looks like it! We might want to add a link to upcoming docs about database support, to make it clear what is supported, but we can look into that closer to release.

4.38 (shipped last Friday) switches Ghost to using `mysql2`, so we support the native MySQL 8 `caching_sha2_password` authentication. AFAIK that would have been one of the last blockers for MySQL 8 support 🙂

**Comment by oliver-la** [comment]
The example for a docker-compose.yml already includes the reference to mysql:8 as stated already. However, there's probably plenty of users running their production Ghost on sqlite3. Are there plans to help users migrate to mysql:8 with a dedicated tool, or is there already a guide to do it manually? sqlite does things differently and I don't really trust a "sqlite to mysql converter" as it might not replicate the database exactly the way Ghost expects it.

**Comment by daniellockyer** [comment]
Hey @oliver-la 🙂 This is something on our list to investigate and look at providing tooling for in the coming months. MySQL is our recommended database for production but we'd certainly like to help smooth the transition over from SQLite.

Ghost content can be exported and reimported via the export/import functionality, but that doesn't cover all data in the database such as members events.

**Comment by tianon** [comment]
I guess we can probably close this now? :eyes:

**Comment by daniellockyer** [comment]
Ghost v5 is out - I'm happy to close this 🙂
