### ISSUE TITLE
publish docker image also to ghcr

### ISSUE THREAD

**Issue by foolioo** [docker-library/ghost#296]
firstly, thank you for all the fine work.
this is more of a request - what do you think of [publishing the docker images to ghcr](https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages) and not only dockerhub?
this will allow to use the latest ghost version without waiting for approval for publishing to dockerhub.

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/issues/8998 (however with the added note that the images are now officially mirrored to ECR Public: https://gallery.ecr.aws/docker).

**Comment by foolioo** [comment]
when using ghcr while ghost code is hosted on github, publishing of docker images into ghcr should be faster than publishing docker images to dockerhub/ecr.

e.g. although [ghost version 4.42.1](https://github.com/TryGhost/Ghost/releases/tag/v4.42.1) was release 4 days ago, the docker images of this version have neither been published to dockerhub, nor ecr.

**Comment by yosifkit** [comment]
The reason for the missing update is that the automated `update.sh` job has been failing to build the images, so nothing has been committed to this repo.

**Comment by foolioo** [comment]
@yosifkit i hope it will get fixed soon, thank you
