### ISSUE TITLE
Ghost fails when trying to register blog

### ISSUE THREAD

**Issue by ryanjm** [docker-library/ghost#3]
When I go to `/ghost` and try to sign up with a new build of this image the page loads, but it fails when I submit the page.

Here is the log from ghost:

```
GET /ghost/api/v0.1/authentication/setup/ 200 15.310 ms - 28

/usr/src/ghost/core/server/mail.js:95
                if (data.error.errno === 'ENOTFOUND') {
                              ^
TypeError: Cannot read property 'errno' of null
    at EventEmitter.<anonymous> (/usr/src/ghost/core/server/mail.js:95:31)
    at EventEmitter.g (events.js:180:16)
    at EventEmitter.emit (events.js:95:17)
    at DirectMailer.<anonymous> (/usr/src/ghost/node_modules/nodemailer/node_modules/directmail/lib/mailer.js:138:30)
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete] (dns.js:147:9)

npm ERR! Linux 3.18.5-tinycore64
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.36
npm ERR! npm  v2.7.0
npm ERR! code ELIFECYCLE
npm ERR! ghost@0.5.9 start: `node index`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the ghost@0.5.9 start script 'node index'.
npm ERR! This is most likely a problem with the ghost package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index
npm ERR! You can get their info via:
npm ERR!     npm owner ls ghost
npm ERR! There is likely additional logging output above.
npm ERR! Linux 3.18.5-tinycore64
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.36
npm ERR! npm  v2.7.0

npm ERR! Uncaught, unspecified "error" event.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/ghost/npm-debug.log
```

I'm going to start looking at additional setup required from Ghost, but if there is any required, it seems like this should be mentioned in the readme.

I'm just running it as apart of my `docker-compose`:

```
ghost:
  image: ghost:0.5.9
  ports:
  - "8080:2368"
```

**Comment by ryanjm** [comment]
Here is the failure message on the webpage itself:

![screen shot 2015-03-13 at 5 25 28 am](https://cloud.githubusercontent.com/assets/90015/6637562/7570cc0c-c941-11e4-8739-21721b4f42cd.png)

It doesn't seem to be a [common error](http://support.ghost.org/ghost-first-run/).

Due to the error log, I'm assuming I probably need to setup a [mail server](http://support.ghost.org/mail). My suggestion for the readme for this image would be to include how to create a basic `config.js` and copy it to this image to get it fully setup. This way people understand that they need that to get going.

**Comment by dummymael** [comment]
@ryanjm can you share your whole config? can't seem to reproduce the error you're getting. I'm also using docker-compose

**Comment by elithrar** [comment]
Having a similar issue here—definitely appears to be a mailer issue:

```sh
GET /ghost/api/v0.1/authentication/setup/ 200 7.287 ms - 28

/usr/src/ghost/core/server/mail.js:95
                if (data.error.errno === 'ENOTFOUND') {
                              ^
TypeError: Cannot read property 'errno' of null
    at EventEmitter.<anonymous> (/usr/src/ghost/core/server/mail.js:95:31)
    at EventEmitter.g (events.js:180:16)
    at EventEmitter.emit (events.js:95:17)
    at DirectMailer.<anonymous> (/usr/src/ghost/node_modules/nodemailer/node_modules/directmail/lib/mailer.js:138:30)
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete] (dns.js:147:9)
```

Is there a way to resolve this? Running it in a container so I can work on a theme without having to mess with any production sites.

**Comment by pascalandy** [comment]
This conversation died. We should close this conversation.

https://github.com/docker-library/ghost/issues/25#issuecomment-247216227
