### ISSUE TITLE
update to 4.46.0

### ISSUE THREAD

**Issue by meal** [docker-library/ghost#303]
there's a 4.46.0 out for some time, but docker image wasn't updated even for 4.45.0

doest this repo needs a maintainer?

**Comment by acburdine** [comment]
@meal no - sometimes the update script fails due to changes in Ghost.

Looks like some of the dependencies changed, I'll work on getting an updated version out soon.

**Comment by acburdine** [comment]
official-images PR: https://github.com/docker-library/official-images/pull/12346
