### ISSUE TITLE
database__connection__filename isn't blank and this causes an error with MySQL

### ISSUE THREAD

**Issue by boycottseattle** [docker-library/ghost#310]
If you watch the log from the container when loaded, you get this error (multiple times):

```Ignoring invalid configuration option passed to Connection: filename. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection```

**Comment by boycottseattle** [comment]
It’s an element inside config.production.json that is prefilled but the docker itself. Normally the variable used there is for the internal SQLite database, but it causes problems with mysql - hence the error in the log.

Perhaps the issue here is that it SHOULD be a variable, one that you can leave blank when using mysql.

See this thread on ghost’s forum: https://forum.ghost.org/t/ignoring-invalid-configuration-option-passed-to-connection-filename-this-is-currently-a-warning-but-in-future-versions-of-mysql2-an-error-will-be-thrown-if-you-pass-an-invalid-configuration-option-to-a-connection/30008/18

**Comment by timscha** [comment]
I can confirm the "issue" with a fresh installation with Mysql 8 und Ghost 5.

**Comment by reraxe** [comment]
I did a fresh installation to migrate from sqlite3 to MySQL:8.0, and it produced the same error.

Fired up sqlite3 service, and back to normal.

I think it could be the `filename` of the sqlite3 config?

```
"database": {
  "client": "sqlite3",
  "connection": {
    "filename": "content/data/ghost-test.db"
  },
  "useNullAsDefault": true,
  "debug": false
}
```

**Comment by ErisDS** [comment]
Does the docker image always run in development mode? That would be bad... 😬

**Comment by tianon** [comment]
We default to `NODE_ENV=production`, but we also default to `sqlite3` (IIRC, that was both for backwards compat and to make the "first timer" experience better?)

You can see our `ghost install` line here:

https://github.com/docker-library/ghost/blob/f1009d6e937cc1050a598b3a63f9384347f370f3/5/debian/Dockerfile#L56

and our `ghost config` lines are also probably relevant:

https://github.com/docker-library/ghost/blob/f1009d6e937cc1050a598b3a63f9384347f370f3/5/debian/Dockerfile#L66-L67

It sounds like we probably do need to do something different here, but I'm not exactly sure _what_ we should change. :see_no_evil:

**Comment by ErisDS** [comment]
As of Ghost 5.0 we no longer support sqlite3 in production. It won't fail to work, but it's not a supported setup and we expect more advanced / scaled features to cease working over time.

I think if you're defaulting to production that indicates that this setup is intended for production installs, in which case only mysql8 is supported.

Maybe it makes sense two have two different installs, so there is a separate one for development with sqlite3 ?

But the correct solution IMO would be to remove the use of sqlite3 in favour of mysql 8 with the config in production mode 🙂

**Comment by blaine07** [comment]
> As of Ghost 5.0 we no longer support sqlite3 in production. It won't fail to work, but it's not a supported setup and we expect more advanced / scaled features to cease working over time.
> 
> I think if you're defaulting to production that indicates that this setup is intended for production installs, in which case only mysql8 is supported.
> 
> Maybe it makes sense two have two different installs, so there is a separate one for development with sqlite3 ?
> 
> But the correct solution IMO would be to remove the use of sqlite3 in favour of mysql 8 with the config in production mode 🙂

I just want to make sure I am clear:

A bit back their was a big ordeal about not being able to use MariaDB. Moved off MariaDB onto MySQL because it was touted as ALL the solution. NOW MySQL isn't the answer and Sqlite3 is? I am quite dense; but just want to make sure I am understanding here?

**Comment by tianon** [comment]
Thanks, @ErisDS!  That makes perfect sense, and in hindsight we probably should've _not_ defaulted to `sqlite3`. :weary:

Now we have an interesting transition problem where we don't really have a great way to communicate to users that the next version of the image might break their setups (we usually use major version bumps for changes to the defaults that are this level of disruptive, but I'm guessing that given how recent 5.0 is that 6.0 is not coming soon :sweat_smile:).  Perhaps this is a big enough deal that we _should_ just break the default configuration and try to document how folks can get the previous setup back?  I'm not sure. :disappointed:

**Comment by blaine07** [comment]
Yes, my setup has invalid config thing BUT it’s a container in Unraid and I have ZERO idea where to look and start with trying to figure out what causes this error in my setup. 🥹

**Comment by ErisDS** [comment]
Hi @tianon, this was a breaking change in Ghost 5.0, which we gave advance notice of here: https://github.com/docker-library/ghost/issues/294.

We have this internal notice that displays in Ghost admin in the case that the env is production and the DB is not mysql8:

<img width="369" alt="CleanShot 2022-08-05 at 12 17 10@2x" src="https://user-images.githubusercontent.com/101513/183090700-38eb658b-547c-4305-a99d-22b5cf17f247.png">

We're currently considering whether this should be a Big Red Banner™️ - but either way, if it could be made possible to detect that the site is running with Docker, we could update this text to be specific and point to specific docs if needed.

**Comment by tianon** [comment]
Yeah, unfortunately, I think we just miscalculated just how much sqlite3 needed to be deprecated. :disappointed:

We haven't pushed 5.8 yet (https://github.com/docker-library/official-images/pull/12926), so I'm going to propose we use 5.8 to apply this breaking change so we can point broken users straight back to 5.7 to give them an easy escape hatch while they figure out how they're going to migrate to MySQL (or adjust their configuration manually to get back to sqlite3).  Thoughts?

**Comment by ErisDS** [comment]
5.7 is totally broken for anyone running in development mode. It's not our best release 😂  Might be best to push 5.8.1 and target 5.9 as the breaking change as I think 5.8.1 is pretty stable.

**Comment by tianon** [comment]
Aha, that's exactly the type of insight I was hoping for :heart:

We'll go ahead with 5.8 then, and we'll work on a draft PR we can merge for 5.9. :+1:
