### ISSUE TITLE
Set SMTP Mail in UI

### ISSUE THREAD

**Issue by phemto5** [docker-library/ghost#315]
I would love to see a SMTP Setting for mail in the UI when running in a container there is no good way to run 'ghost restart' so you can edit the config but not make it the running config.

this is a good example of the changes made
https://visioun.com/blog/configure-smtp-for-outbound-emails-ghost-smtp-setup/

**Comment by acburdine** [comment]
@phemto5 I'm not sure there's anything we can do in the Docker container itself for this, adding functionality within the UI would require changes to Ghost itself.

Ghost does have a forum though! https://forum.ghost.org/ Feel free to go there and post your idea 😄 

Going to close this for now as it's not something that's realistically doable within this docker image.

**Comment by phemto5** [comment]
I will take this to the Ghost developers. Thanks!
