### ISSUE TITLE
New 5.9.3 Breaks previous version 5 ghost installs

### ISSUE THREAD

**Issue by LiamSx45** [docker-library/ghost#327]
Error when updating to the new version from a older version that did not use a dedicated database.

`
[2022-08-17 08:55:32] INFO Ctrl+C to shut down
[2022-08-17 08:55:32] INFO Ghost server started in 0.833s
[2022-08-17 08:55:32] ERROR connect ECONNREFUSED 127.0.0.1:3306
connect ECONNREFUSED 127.0.0.1:3306
"Unknown database error"
Error ID:
    500
Error Code: 
    ECONNREFUSED
Error: connect ECONNREFUSED 127.0.0.1:3306
    at /var/lib/ghost/versions/5.9.4/node_modules/knex-migrator/lib/database.js:57:19
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
[2022-08-17 08:55:32] WARN Ghost is shutting down
[2022-08-17 08:55:32] WARN Ghost has shut down
[2022-08-17 08:55:32] WARN Your site is now offline
[2022-08-17 08:55:32] WARN Ghost was running for a few seconds
`

**Comment by trivarialthea** [comment]
Can confirm too. Any fix or migration steps?

**Comment by trivarialthea** [comment]
Ok, so i converted my sqlite database to an mysql one. Set an mysql server and connected it to that mysql server...
That fixed it and it is up and running again!

**Comment by mjkl-gh** [comment]
Just ran into this, I'm one of those lazy people running watchtower and ghost:latest

Anyhow documentation now states Mysql is the default and sqlite requires configuration:

https://ghost.org/docs/config/#database

I think they changed this in the last version. I reverted back to 5.7 and it work. Will try to properly define my sqlite3 db and see if that fixes it for 5.9.3 and 5.9.4

**Comment by mjkl-gh** [comment]
https://github.com/docker-library/ghost/pull/323#issuecomment-1212554428

This was pushed 14 hours ago. with instructions

**Comment by LiamSx45** [comment]
I switched my ghost services to use mysql but I noticed a huge memory increase. Before my machine was using ~50% of my memory and now it is using 80%. Any ideas on this?

**Comment by mjkl-gh** [comment]
running

`docker stats`

Will report resource usage  per [link](https://docs.docker.com/engine/reference/commandline/stats/)

**Comment by LiamSx45** [comment]
I am using a stack for each ghost website I have and using mariadb. When I was using sqlite, my memory usage was about 3.5gigs. After switching all the sites to mariadb, the memory usage was 7.8gigs

**Comment by tianon** [comment]
Indeed, this was unfortunately intentional, and should've been applied from 5.0 onwards (as noted in https://github.com/docker-library/ghost/pull/323#issuecomment-1218255673).
