### ISSUE TITLE
updating Ghost Image from 4.8.3 to 4.9 causes failures

### ISSUE THREAD

**Issue by kunalbabre** [docker-library/ghost#329]
updating Ghost Image from 4.8.3 to 4.9 causes failures

ghost Error: connect ECONNREFUSED 127.0.0.1:3306     at /var/lib/ghost/versions/5.9.4/node_modules/knex-migrator/lib/database.js:57:19     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)

**Comment by tianon** [comment]
See https://github.com/docker-library/ghost/pull/323, especially https://github.com/docker-library/ghost/pull/323#issuecomment-1212554428.
