### ISSUE TITLE
Just a question about newest ghost version.

### ISSUE THREAD

**Issue by paulknulst** [docker-library/ghost#334]
As the Ghost development team cares about updating to a new version would it be sufficient to change
```
ENV GHOST_VERSION 5.14.2
```

to

```
ENV GHOST_VERSION 5.16
```

to update my ghost blog to the current version?

**Comment by yosifkit** [comment]
If you want to build your own images, sure. The images here should get automatic updates to newer versions, but the CI was stuck during testing on a change in how `ghost` handles a get request for `//` (https://github.com/docker-library/ghost/issues/335 and https://github.com/docker-library/official-images/pull/13233).

**Comment by yosifkit** [comment]
See also: https://github.com/docker-library/ghost#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

https://github.com/docker-library/official-images/pull/13237

**Comment by paulknulst** [comment]
Thank you very much for that information :) Thanks for updating the image.
