### ISSUE TITLE
Update job has been stuck for 9 days

### ISSUE THREAD

**Issue by BlackCetha** [docker-library/ghost#335]
I was waiting for the new tags from upstream to become available for quite a while now.
After digging a bit, i found the Jenkins Job that seems to be responsible for generating new Tags. It seems to be stuck:
https://doi-janky.infosiftr.net/job/update.sh/job/ghost/8794/console

**Comment by yosifkit** [comment]
Thanks! I killed the problematic job. Should have updated Dockerfiles soon.

**Comment by BlackCetha** [comment]
Thanks for your quick response. I had another look at the build job just now, and unfortunately it seems like it is stuck once again.

**Comment by yosifkit** [comment]
I have a fix to prevent that sticking in the future: https://github.com/docker-library/official-images/pull/13233
