### ISSUE TITLE
server__port env value seems not working

### ISSUE THREAD

**Issue by jesseXu** [docker-library/ghost#336]
I'm trying to change the default port with the latest Ghost image:
`docker run -d --name some-ghost -e NODE_ENV=development -e url=http://localhost:3001 -e server__port=2355 -p 3001:2355 ghost`

and the running result seems still using the port 2368:

`CONTAINER ID   IMAGE     COMMAND                  CREATED         STATUS         PORTS                              NAMES`
`f2d85a146c8f   ghost     "docker-entrypoint.s…"   3 seconds ago   Up 2 seconds   2368/tcp, 0.0.0.0:3001->2355/tcp   some-ghost`

**Comment by tianon** [comment]
That's due to the `EXPOSE` directive in the original `Dockerfile`, and should be totally safe to ignore (the container shouldn't actually be using 2368 in your configuration).
