### ISSUE TITLE
How to migrate all data from Ubuntu installed to Docker compose.

### ISSUE THREAD

**Issue by yang-lile** [docker-library/ghost#338]
I backup to a zip file by `ghost backup`. How can i restore data to running docker image.

**Comment by wglambert** [comment]
You can unzip it and mount your existing content to `/var/lib/ghost/content`:
`docker run -d --name some-ghost -e NODE_ENV=development -p 3001:2368 -v /path/to/ghost/blog:/var/lib/ghost/content ghost:alpine`
https://github.com/docker-library/docs/tree/master/ghost#stateful

While it's running isn't ideal as it should be initialized off the pre-populated data

**Comment by yang-lile** [comment]
Yes, it not ideal. I still need to login, my posts are gone. I login and import my content.json file, posts has a initial post named come soon(is repeated but does not affect). 
![图片](https://user-images.githubusercontent.com/35729940/197030589-28006781-8a0a-48b8-988f-292e03791333.png)
finally imort theme. maybe manully migrate data is stupid, but can run ... 
backup is still useful for the backup of image resources. I hope the data migration can be simpler and more stable in the future. Thanks for @wglambert 's solution

**Comment by yang-lile** [comment]
version
origin version: 5.15.0
migration version: 5.19.3

some warning in picture, are normal things.
