### ISSUE TITLE
SIGTERM signal-forward

### ISSUE THREAD

**Issue by ChasonTang** [docker-library/ghost#37]
Ghost have handlers for SIGTERM and SIGINT.It is work in server.However,npm break the forward of SIGTERM in Docker container.

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
user         1  2.1  2.5 1076200 52648 ?       Ssl  02:17   0:00 npm
user        39  0.0  0.0   4340   764 ?        S    02:17   0:00 sh -c node index
user        40 13.5  5.5 1251604 113132 ?      Sl   02:17   0:03 node index
root        49  1.5  0.1  20228  3008 ?        Ss   02:18   0:00 /bin/bash
root        54  0.0  0.1  17500  2140 ?        R+   02:18   0:00 ps aux
```

npm is the process which PID is 1,it can't forward SIGTERM to node process.when I type `docker stop ghost` to close the container,it will last 10 seconds then send the SIGKILL to close the container rudely.
Would it is helpful that using `node index` instead of using `npm start`

**Comment by tianon** [comment]
Sorry for not seeing this sooner :disappointed:

The discussion on https://github.com/docker-library/ghost/pull/35 is relevant -- namely, Ghost 1.x fixes this by invoking `node current/index.js` directly rather than going through `npm`. :+1:
