### ISSUE TITLE
Docker run is failing with error

### ISSUE THREAD

**Issue by vishnu-kvnvv** [docker-library/ghost#375]
I have copied the [Dockerfile](https://github.com/docker-library/ghost/blob/master/5/debian/Dockerfile) and [docker-entrypoint.sh](https://github.com/docker-library/ghost/blob/master/5/debian/docker-entrypoint.sh) 
Build was successfull with 
```
docker build . -t ghost-docker-test:initial
```
Trying to run using
```
docker run -d --name ghost -p 8080:2368  ghost-docker-test:initial
```

The run is failing
```
f4f6ca353b3e20c625e25f0b78af6f1c15d06db50f0002d4fa53e5930ffceda3
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "docker-entrypoint.sh": executable file not found in $PATH: unknown.
```

Need the help with this

**Comment by wglambert** [comment]
If you downloaded the repo's files with something other than `git clone` then the execute permissions on the docker-entrypoint.sh won't be persisted.
https://github.com/docker-library/postgres/issues/386#issuecomment-350323371
https://github.com/docker-library/postgres/issues/296#issuecomment-308735942

**Comment by vishnu-kvnvv** [comment]
Thanks @djerfy,
Your suggestion worked
