### ISSUE TITLE
5.43.0 Released without AMD tags

### ISSUE THREAD

**Issue by danquack** [docker-library/ghost#379]
The latest release 5.43.0 was released to docker hub, and did not have any AMD builds. Is AMD no longer supported, or was this a partial/poison deploy?

**Comment by yosifkit** [comment]
This is perfectly normal; some builds sometimes take longer than others (especially when the queue is full of everything rebuilding from the Debian bump yesterday in https://github.com/docker-library/official-images/pull/14428).  The manifest list will be updated as other architecture builds are completed.
