### ISSUE TITLE
Release 0.9 is up

### ISSUE THREAD

**Issue by pascalandy** [docker-library/ghost#38]
Question for releases in general. 

When should we see this `Dockerfile` updated after the Ghost Foundation released something on their side? Per example this commit: https://github.com/TryGhost/Ghost/commit/e203eb8fb378f44542271fd5074d669ad75641c8

I'm running 0.7.9 and I can't wait to see 0.9 !! I'm asking this with gratitude, not as a request :)

Cheers!
Pascal

**Comment by sasvdw** [comment]
I have made the change and the PR has been merged but I'm not sure if I had missed something as to how the image on docker hub actually gets updated.

**Comment by pascalandy** [comment]
I think it's as simple as that but that's why I gently asked here - https://github.com/docker-library/ghost/issues/38
