### ISSUE TITLE
ETA On ghost:5.54.2 docker container image in dockerhub?

### ISSUE THREAD

**Issue by BlankFoxGirl** [docker-library/ghost#388]
Hey all,

What's the mean TTL between a version update merged against master, and the subsequent image version being pushed to dockerhub?

**Comment by BlankFoxGirl** [comment]
Note: For those looking to build the current version of the ghost image, you can run the following command (aimed at those unfamiliar with docker).

```shell
cd 5/alpine && docker build -t ghost:5.54.2-alpine .
```

**Comment by yosifkit** [comment]
The Readme has a little [section](https://github.com/docker-library/ghost/tree/10748353aafc177f4378aa14c1a02ee12563bebb#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet) on this. The answer is soon (hopefully later today).
