### ISSUE TITLE
ghost:5.65-alpine: no matching manifest for linux/arm/v7 in the manifest list entries

### ISSUE THREAD

**Issue by brunoais** [docker-library/ghost#392]
Is there something wrong with some script? I can't update ghost to any version between 5.61-5.65.

----------
Just for debugging purposes, I can confirm the amd64 version is being created

**Comment by yosifkit** [comment]
It looks like the Alpine images are failing to build on non-amd64 architectures since after `5.60.0` (at `5.61.2` since that is the next version we added): https://doi-janky.infosiftr.net/job/multiarch/view/images/view/ghost/.  I'm digging in to find a fix.

**Comment by yosifkit** [comment]
Fix in https://github.com/docker-library/ghost/pull/393
