### ISSUE TITLE
Missing ARM Tags for Docker Image 5.76.2

### ISSUE THREAD

**Issue by ChristophWeigert** [docker-library/ghost#405]
Hi,

previous images ([5.76.0](https://hub.docker.com/layers/library/ghost/5.76.0/images/sha256-6483222b77c87867c41205472f8af5a643acc8b49a6f96bb59ae182645583a97?context=explore), [5.76.1](https://hub.docker.com/layers/library/ghost/5.76.1/images/sha256-43cfbc513a33e341fe04ad89b504b6eeb5bf6f8b92b8c6235a89a516f497e766?context=explore)) had ARM based images. For the current latest ([5.76.2](https://hub.docker.com/layers/library/ghost/5.76.2/images/sha256-a95049895db6e87a03f8071ba5194b51c9279c395fa5214ac6587687ca7c4355?context=explore)) there are not ARM tags. Can those be provided again?

**Comment by tianon** [comment]
Doh, we had a glitch in the build servers - it's fixed now, and builds are in progress.

**Comment by tianon** [comment]
Fixed now :+1:
