### ISSUE TITLE
Ghost docker image build

### ISSUE THREAD

**Issue by rusty1281** [docker-library/ghost#416]
Hello all,

Was just wondering can we get any eta on the updated ghost docker image? Seem the last version update was a month ago with the same 5.82.2 version image being update a few days go. Considering the 5.82.10 is out, I was just wondering if there is some major issue with this image build or what?

Thank you in advance!

**Comment by yosifkit** [comment]
The image fails to run with any of the updates. You can see some tests in https://github.com/docker-library/ghost/pull/415. @LaurentGoderre is working with upstream to get fixes in https://github.com/TryGhost/Ghost/issues/20065.

**Comment by rusty1281** [comment]
Thank you! I have seen this topic as well the other day but wanted to see if and when it will be fixed. Seen just now that 10min ago that Laurent confirmed the fix is working. Nice one!

Tnx again!
