### ISSUE TITLE
missing architectures on 'full version' tags

### ISSUE THREAD

**Issue by remcoros** [docker-library/ghost#418]
I'm using the "patch version" tags (5.85.2) to pull docker images in a multi-arch build.

But these tags are missing some architectures (arm64 for example).
You can see it here: https://hub.docker.com/_/ghost/tags

while 'latest', '5.85' and '5' all have amd + arm builds, the '5.85.2' tag does not. 

This breaks my multi-arch build as seen here: https://github.com/remcoros/ghost-startos/actions/runs/9615892103/job/26524160498#step:4:142

I'm temporarily working around it by using the '5.85' tag, but prefer to pin it to the exact version.

edit: actually, I think the 5.85.2 version of Ghost doesn't have a container build and tagged for arm64.

**Comment by LaurentGoderre** [comment]
The arm64 variant is probably being built right now

**Comment by remcoros** [comment]
Thanks, I see more arm builds appearing now. Guess I am too quick updating 🤣
