### ISSUE TITLE
Switch from 0.7.9 to 0.10.0 failed

### ISSUE THREAD

**Issue by aholbreich** [docker-library/ghost#42]
After switch of 
0.7.9 version to 0.10.0

i get the following exception on start

```
npm info it worked if it ends with ok
npm info using npm@2.15.9
npm info using node@v4.5.0
npm info prestart ghost@0.10.0
npm info start ghost@0.10.0

> ghost@0.10.0 start /usr/src/ghost
> node index

Migrations: Creating database backup

 ERROR: select count(distinct posts.id) as aggregate from "posts" where "posts"."visibility" = 'public' and "posts"."page" = true and "posts"."status" = 'published' - SQLITE_ERROR: no such column: posts.visibility 

 Error: select count(distinct posts.id) as aggregate from "posts" where "posts"."visibility" = 'public' and "posts"."page" = true and "posts"."status" = 'published' - SQLITE_ERROR: no such column: posts.visibility
    at Error (native) 

npm info poststart ghost@0.10.0
npm info ok 
```

What went wrong and how should i upgrade this?

**Comment by yosifkit** [comment]
What files are you saving from the old container (any volumes)?  Most likely you'll need to follow similar steps to http://support.ghost.org/how-to-upgrade. This seems relevant:

>When upgrading through minor versions, e.g. 0.8.0/0.9.0/0.10.0, there are database migrations to run. It is best to do these one-at-a-time and always use `npm start –production` afterwards to check the migrations run successfully.

Most likely it will be just a series of `docker run -it --rm -v /important/stuff/:/var/lib/ghost/themes/ ghost:version`  but may vary on how you are mounting the files and might require deleting some of them.

**Comment by aholbreich** [comment]
Applying One after another
0.7.9 --> 0.8.0 --> 0.9.0--> 0.10.0 fixed the problem!
Thank you.

**Comment by pascalandy** [comment]
Good to know !

> Applying One after another
0.7.9 --> 0.8.0 --> 0.9.0--> 0.10.0 fixed the problem!
