### ISSUE TITLE
manifest for ghost:latest not found

### ISSUE THREAD

**Issue by tchin25** [docker-library/ghost#427]
Running `docker pull ghost` or other variations `ghost:5`, `ghost:latest` fails

```
$ docker pull ghost
Using default tag: latest
latest: Pulling from library/ghost
manifest for ghost:latest not found: manifest unknown: manifest unknown
```

I tried this on Windows 11, Ubuntu 22.04, and also in [Coolify (self-hosted and cloud)](https://github.com/coollabsio/coolify/issues/4501#issuecomment-2542917785)

**Comment by jjjonesjr33** [comment]
Same here, using official image on unraid.
```yaml
Pulling image: ghost:latest
IMAGE ID [1235004124]: Pulling from library/ghost.

TOTAL DATA PULLED: 0 B

Error: manifest for ghost:latest not found: manifest unknown: manifest unknown
```

**Comment by sanderdatema** [comment]
It seems using `latest` is discouraged, as it's not a real tag. More and more devs stop using it, maybe Ghost did as well. You'd be better of using an existing tag. And yes, every time there's a new one, you'd have to edit your `docker-compose.yml`.

**Comment by Proximus888** [comment]
> It seems using `latest` is discouraged, as it's not a real tag. More and more devs stop using it, maybe Ghost did as well. You'd be better of using an existing tag. And yes, every time there's a new one, you'd have to edit your `docker-compose.yml`.
> 
> Edit: even other tags don't seem to work anymore. So something else might be going on here...

It's not just the ```latest``` tag that is causing issues. I use the ```5``` tag and have the same issue.

```
sudo docker pull ghost:5                                                                  
5: Pulling from library/ghost                                                               
manifest for ghost:5 not found: manifest unknown: manifest unknown
```

**Comment by davidelng** [comment]
For now using a precise tag works, I specified “ghost:5.104.2-alpine” in my docker compose and it went up. Maybe tag 5 has some problems regarding the manifest.

**Comment by F117aDriver** [comment]
I confirm docker pull ghost:5:105.0 cannot find the manifest. Pulling any tag associated with 104.2 finds the manifest. Sounds like the 105.0 build is bad...

**Comment by thaJeztah** [comment]
This looks to be the same cause as the ticket below (for another repository); the team is actively working on this;


- https://github.com/docker-library/docker/issues/519

**Comment by LaurentGoderre** [comment]
Closing in favor of the above mentioned issue.

**Comment by thaJeztah** [comment]
Update on this issue; a colleague confirmed that the list of official images should be all processed. The verification script will still be running for some hours, but we're updating the statuspage to "monitoring"

There may be some images in the platform-specific orgs that are used as intermediate image that may not yet be addressed, and (given much lower / corner-case use), e.g. images in the platrform-specific namespace (e.g. https://hub.docker.com/u/arm64v8/, and other similar namespaces listed in; https://github.com/docker-library/official-images#architectures-other-than-amd64. Those namespaces are effectively intermediate stages for the multi-platform images. These images will likely be processed later, which may be done after the weekend.
