### ISSUE TITLE
gpg error

### ISSUE THREAD

**Issue by lobocode** [docker-library/ghost#45]
gpg: keyring `/tmp/tmp.Le9rzhBiPt/secring.gpg' created
gpg: keyring `/tmp/tmp.Le9rzhBiPt/pubring.gpg' created
gpg: requesting key BF357DD4 from hkp server ha.pool.sks-keyservers.net
?: ha.pool.sks-keyservers.net: Network is unreachable
gpgkeys: HTTP fetch error 7: couldn't connect: Network is unreachable
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0

What's this?

**Comment by tianon** [comment]
Can I ask why you're building the repo from source instead of just pulling the pre-built images?

Regardless, the likely cause for the build issue you've shared is a firewall blocking access to the GPG keyservers.

**Comment by lobocode** [comment]
It's the pre-built version use version 0.10.0. Version 0.10.1 fix many errors of 0.10.0 and doesn't contain pre-built version.

;)

**Comment by tianon** [comment]
As of a few minutes ago (https://github.com/docker-library/official-images/pull/2131, to be precise), the pre-built image is updated to 0.10.1. :+1:

**Comment by lobocode** [comment]
@tianon thanks :+1:
