### ISSUE TITLE
Using base image: Alpine 3.4 / Node v4.5.0 / NPM_VERSION=2

### ISSUE THREAD

**Issue by pascalandy** [docker-library/ghost#46]
- https://github.com/mhart/alpine-node/blob/c447925032bf2a8d7a8bddb55612a2583f809035/Dockerfile
- https://hub.docker.com/r/mhart/alpine-node/

Seeing that Nginx is maintaining both (Ubuntu Jessie and Alpine), I started to use the Alpine lately.

Regarding this Ghost Dockerfile, I have to admit that I don't have the courage to convert the current Jessie image into an Alpine one.

Cheers!

**Comment by yosifkit** [comment]
Node upstream is still working on Alpine support: https://github.com/nodejs/docker-node/issues/46.

**Comment by pascalandy** [comment]
Looks like the alpine image is ready :)
https://github.com/nodejs/docker-node/blob/master/4.7/alpine/Dockerfile

**Comment by pascalandy** [comment]
Node V6 is now recommended: https://github.com/docker-library/ghost/issues/58
