### ISSUE TITLE
allow to set HTTP headers

### ISSUE THREAD

**Issue by babatundebusari** [docker-library/ghost#49]
allow to set headers officially on expressjs which powers the ghost application

Why?

In the world of microservices, it is best to set response headers right from the source(application) 
will be great to be able to set HTTP headers right from running ghost container which is powered by expressjs so one can troubleshoot at the microservices layer.

How?

http://expressjs.com/en/4x/api.html#setHeaders

**Comment by tianon** [comment]
We provide a pretty stock installation of Ghost -- if Ghost itself allows this, our image should expose that behavior in the standard way.  I'd recommend checking the Ghost documentation for more information (and possibly joining their Slack channel via http://slack.ghost.org/ for additional help). :+1:
