### ISSUE TITLE
Recommanded version is Node V6

### ISSUE THREAD

**Issue by pascalandy** [docker-library/ghost#58]
I believe we should use node6 as the image base.

> Ghost no longer supports Node.js v0.12. It's is no longer maintained as of 31st December 2016. We will continue to recommend using Node v4 with Ghost for the time being - even that this version is not the version recommended for most users by Node.js, **it's v6**.

source: https://dev.ghost.org/ghost-0-11-4/

**Comment by tianon** [comment]
From the bit you quoted:

> We will continue to recommend using Node v4 with Ghost for the time being

So, I think we really should stick with the Ghost recommendations, regardless of the Node.js recommendations.

**Comment by tianon** [comment]
Also, from http://support.ghost.org/supported-node-versions/

> The recommended version of Node to use with Ghost is currently Node v4 LTS.

**Comment by pascalandy** [comment]
You're right! I missed read that.
