### ISSUE TITLE
Official support for external storage like Amazon S3 et cetera

### ISSUE THREAD

**Issue by babatundebusari** [docker-library/ghost#61]
It has been noted here https://github.com/TryGhost/Ghost/wiki/Using-a-custom-storage-module that external storage can now be used with ghost but the official docker image (this project) does not come with this built-in.

Any plan to PLEASE help support this and include in official image?

Will really be one of the best features of 2017!

**Comment by pascalandy** [comment]
I think it's out of scope regarding this Docker image.

**Comment by SISheogorath** [comment]
You should be able to extend this image to support it without a problem. That's the better way to add this feature if you need it.

**Comment by tianon** [comment]
Agree with @pascalandy and @SISheogorath -- extending this image would be the way I'd recommend going for that. :+1: :heart:
