### ISSUE TITLE
will this work with $5 digital ocean plan(question)

### ISSUE THREAD

**Issue by jasan-s** [docker-library/ghost#62]
Digital Ocean one click ghost required $10 plan, Additionally, is there any guide to get this up and running on Digital Ocean.

**Comment by SISheogorath** [comment]
Yes, the official ghost image works on 512MB droplets.

The DO 1-click-app needs a 1G droplet because they use `npm install` which runs out of memory on a 512MB droplet. But you can install ghost on an 512MB droplet using `npm install` by adding Swap.

**Comment by jasan-s** [comment]
@SISheogorath  is there any guide to installing Ghost using Swap?  I also read that it can be dangerous using Swap on SSD is that true?

**Comment by SISheogorath** [comment]
See: https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04

All information are provided including a warning. Then you can follow the regular guides to install ghost on Digital Ocean. 

Good news: You can remove swap after installing ghost. But you need it for updates.

**Comment by pascalandy** [comment]
Make sense @SISheogorath :)

**Comment by tianon** [comment]
Thanks @SISheogorath :+1:
