### ISSUE TITLE
Official Ghost Container - No More Override?

### ISSUE THREAD

**Issue by kellington** [docker-library/ghost#7]
With the transition from [dockerfile/ghost](https://github.com/dockerfile/ghost), the official containers on Docker Hub no longer support the "ghost-override".   

What is the recommended method to have user data outside of the container for easy backup?

**Comment by yosifkit** [comment]
There is a PR to make similar functionality: https://github.com/docker-library/ghost/pull/6.  This would allow you to mount your 'apps, 'images', 'data', or 'themes' into the `GHOST_CONTENT` dir (`/var/lib/ghost`).  Does that cover what you need?

**Comment by c0deMike** [comment]
I actually stumbled upon this issue myself yesterday. #6 would cover my needs.

**Comment by kellington** [comment]
Yes - I just figured this out and updated my docker-compose.yml to include:
  volumes:
    - /home/admin/DockerAnalytics/ghost-vols:/var/lib/ghost

Thanks
