### ISSUE TITLE
Feature Request: Custom Config File Location

### ISSUE THREAD

**Issue by jtcressy** [docker-library/ghost#73]
Hi, 

We currently have no way of persisting the config.*.json files in /var/lib/ghost. The only volume we can mount is /var/lib/ghost/content. Upstream ghost has not implemented a custom config file location option, with either a command-line argument or environment variable.

What I propose is two (or three) different methods:
1. ENV and Symbolic link
    - Establish an environment variable, ``GHOST_CONFIG`` that optionally contains a path to a config file, e.g. ``/config/config.production.json``
    - Symlink the file in the entrypoint.sh with ``ln -fs $GHOST_CONFIG /var/lib/ghost/GHOST_CONFIG``

2. Volume and Symbolic link

    a. 
    - Create new volume at ``/config``
    - Symlink ``/config/config.*.json`` to ``/var/lib/ghost/config.*.json``
        - ``ln -fs /config/config.*.json /var/lib/ghost/config.*.json``

    b.
    - Just symlink ``/var/lib/ghost/content/config.*.json`` to ``/var/lib/ghost/config.*.json``
        - ``ln -fs /var/lib/ghost/content/config.*.json /var/lib/ghost/config.*.json``

My favorite method would be 2a. This enables users of both docker compose and kubernetes to manage their config files. Docker compose can just mount another volume, and kubernetes users can make use of ConfigMaps and mount them in their own dedicated directory.

I would gladly submit a pull request, but i'm unsure if I should make edits to each version of ghost (1.0-1.5) or just the latest (1.5). All we'd have to do is add some code to the entrypoint.sh and an ENV + VOLUME clause to the Dockerfile.

**Comment by SISheogorath** [comment]
What version of Ghost are you talking about?

* 0.11 automatically links the config.js to the correct location.
* 1.0+ allows you to configure ghost by [environment variables](https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables)

Where do you need more config?

**Comment by acburdine** [comment]
@jtcressy Going to close this because, as @SISheogorath noted, Ghost supports configuration via environment variables (see the above shared link).
