### ISSUE TITLE
configuring via environment variables does not work

### ISSUE THREAD

**Issue by smoebody** [docker-library/ghost#75]
regarding #73 i configured the container with an environment variable

    URL=https://example.com/

After startup (removed old container) the generated links on the page (tags, rss) still show http://localhost:2368.

Also the startup messages say

    Your blog is now available on http://localhost:2368/

executing a shell in the container shows the environment variable though

```
# env
GHOST_INSTALL=/var/lib/ghost
NODE_VERSION=6.11.2
HOSTNAME=39c60a570f9e
TERM=xterm
VIRTUAL_PORT=2368
NPM_CONFIG_LOGLEVEL=warn
GHOST_VERSION=1.5.0
GHOST_CONTENT=/var/lib/ghost/content
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/var/lib/ghost
NODE_ENV=production
URL=https://example.com/
```

**Comment by acburdine** [comment]
@smoebody It does work - it's a bit weird though, the environment variables have to be lowercased, e.g. `url=https://example.com`. Sorry for the confusion!

**Comment by celebrion** [comment]
Whas about to type the same thing! The env stuff can be found here:
https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
(All lower-case everywhere...)

**Comment by smoebody** [comment]
thanks for clarifying. i now can confirm that it works. One should correct the ghost docs at https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables. The examples given there are misleading.
