### ISSUE TITLE
Cannot access `casper` directory via the recommended volume mounting settings

### ISSUE THREAD

**Issue by cowchimp** [docker-library/ghost#76]
Hi.

The current Readme for the image specifies that you should mount the `/var/lib/ghost/content` folder.
However, `/var/lib/ghost/content/themes/casper` is a link to somewhere else in the container, which means you can't mount files to there.
Is there a recommended way to mount files to effect the casper theme?

Thanks.

**Comment by tianon** [comment]
I _think_ the best way to customize the casper theme would be to remove the
symlink, copy the directory it points to, then make your changes there (or
make a new theme based on casper instead).

**Comment by DeciderWill** [comment]
When deploying 1.5.1, 1.5 or 1 casper cannot be accessed.
`[2017-08-09 14:05:11] [36mINFO[39m Creating table: posts 
[2017-08-09 14:05:11] [36mINFO[39m Creating table: users 
[2017-08-09 14:05:11] [36mINFO[39m Creating table: roles 
[2017-08-09 14:05:11] [36mINFO[39m Creating table: roles_users 
[2017-08-09 14:05:11] [36mINFO[39m Creating table: permissions 
[2017-08-09 14:05:11] [36mINFO[39m Creating table: permissions_users 
[2017-08-09 14:05:11] [36mINFO[39m Creating table: permissions_roles 
[2017-08-09 14:05:11] [36mINFO[39m Creating table: permissions_apps 
[2017-08-09 14:05:11] [36mINFO[39m Creating table: settings 
[2017-08-09 14:05:11] [36mINFO[39m Creating table: tags 
[2017-08-09 14:05:11] [36mINFO[39m Creating table: posts_tags 
[2017-08-09 14:05:11] [36mINFO[39m Creating table: apps 
[2017-08-09 14:05:11] [36mINFO[39m Creating table: app_settings 
[2017-08-09 14:05:11] [36mINFO[39m Creating table: app_fields 
[2017-08-09 14:05:11] [36mINFO[39m Creating table: clients 
[2017-08-09 14:05:11] [36mINFO[39m Creating table: client_trusted_domains 
[2017-08-09 14:05:11] [36mINFO[39m Creating table: accesstokens 
[2017-08-09 14:05:11] [36mINFO[39m Creating table: refreshtokens 
[2017-08-09 14:05:11] [36mINFO[39m Creating table: subscribers 
[2017-08-09 14:05:11] [36mINFO[39m Creating table: invites 
[2017-08-09 14:05:11] [36mINFO[39m Creating table: brute 
[2017-08-09 14:05:11] [36mINFO[39m Model: Post 
[2017-08-09 14:05:11] [36mINFO[39m Model: Tag 
[2017-08-09 14:05:11] [36mINFO[39m Model: Client 
[2017-08-09 14:05:11] [36mINFO[39m Model: Role 
[2017-08-09 14:05:11] [36mINFO[39m Model: Permission 
[2017-08-09 14:05:11] [36mINFO[39m Model: User 
[2017-08-09 14:05:12] [36mINFO[39m Relation: Role to Permission 
[2017-08-09 14:05:12] [36mINFO[39m Relation: Post to Tag 
[2017-08-09 14:05:12] [36mINFO[39m Relation: User to Role 
[2017-08-09 14:05:12] [36mINFO[39m Finished database migration! 
[2017-08-09 14:05:14] [31mERROR[39m
[31m
[31mNAME: ThemeValidationError[39m
[31mMESSAGE: The currently active theme "casper" is invalid.[39m

[37mlevel:[39m[37mnormal[39m

[31mERROR DETAILS:
    """
      [
      	{
      		"fatal": true,
      		"level": "error",
      		"rule": "Replace the <code>{{image}}</code> helper with <code>{{img_url feature_image}}</code> or <code>{{img_url profile_image}}</code>",
      		"details": "The <code>{{image}}</code> helper was replaced with <code>{{img_url}}</code>.<br>Depending on the context of the <code>{{img_url}}</code> helper you would need to use e. g. <br><br><code>{{#post}}<br>&nbsp;&nbsp;&nbsp;&nbsp;{{img_url feature_image}}<br>{{/post}}</code><br><br>to render the feature image of the blog post.<br>Find more information about the <code>{{img_url}}</code> helper <a href=\"https://themes.ghost.org/docs/img_url\" target=_blank>here</a> and read more about Ghost's usage of contexts <a href=\"https://themes.ghost.org/docs/context-overview\" target=_blank>here</a>.",
      		"failures": [
      			{
      				"ref": "post.hbs",
      				"message": "Please remove or replace {{image}} from this template"
      			}
      		],
      		"code": "GS001-DEPR-IMG"
      	},
      	{
      		"fatal": true,
      		"level": "error",
      		"rule": "Replace the <code>{{author.image}}</code> helper with <code>{{author.profile_image}}</code>",
      		"details": "The <code>image</code> attribute in author context was replaced with <code>profile_image</code>.<br>Instead of <code>{{author.image}}</code> you need to use <code>{{author.profile_image}}</code>.<br>See the object attributes of <code>author</code> <a href=\"https://themes.ghost.org/docs/author-context#section-author-object-attributes\" target=_blank>here</a>.",
      		"failures": [
      			{
      				"ref": "partials/loop.hbs",
      				"message": "Please remove or replace {{author.image}} from this template"
      			}
      		],
      		"code": "GS001-DEPR-AIMG"
      	},
      	{
      		"fatal": true,
      		"level": "error",
      		"rule": "Replace the <code>{{@blog.cover}}</code> helper with <code>{{@blog.cover_image}}</code>",
      		"details": "The <code>cover</code> attribute was replaced with <code>cover_image</code>.<br>Instead of <code>{{@blog.cover}}</code> you need to use <code>{{@blog.cover_image}}</code>.<br>See <a href=\"https://themes.ghost.org/docs/blog\" target=_blank>here</a>.",
      		"failures": [
      			{
      				"ref": "index.hbs",
      				"message": "Please remove or replace {{@blog.cover}} from this template"
      			},
      			{
      				"ref": "tag.hbs",
      				"message": "Please remove or replace {{@blog.cover}} from this template"
      			}
      		],
      		"code": "GS001-DEPR-BC"
      	},
      	{
      		"fatal": true,
      		"level": "error",
      		"rule": "Replace the <code>{{tag.image}}</code> helper with <code>{{tag.feature_image}}</code>",
      		"details": "The <code>image</code> attribute in tag context was replaced with <code>feature_image</code>.<br>Instead of <code>{{tag.image}}</code> you need to use <code>{{tag.feature_image}}</code>.<br>See the object attributes of <code>tags</code> <a href=\"https://themes.ghost.org/docs/tag-context#section-tag-object-attributes\" target=_blank>here</a>.",
      		"failures": [
      			{
      				"ref": "tag.hbs",
      				"message": "Please remove or replace {{tag.image}} from this template"
      			}
      		],
      		"code": "GS001-DEPR-TIMG"
      	},
      	{
      		"fatal": true,
      		"level": "error",
      		"rule": "Replace the <code>{{#if image}}</code> helper with <code>{{#if feature_image}}</code>, or <code>{{#if profile_image}}</code>",
      		"details": "The <code>image</code> attribute was replaced with <code>feature_image</code> and <code>profile_image</code>.<br>Depending on the <a href=\"https://themes.ghost.org/docs/context-overview\" target=_blank>context</a> you will need to replace it like this:<br><br><code>{{#author}}<br>&nbsp;&nbsp;&nbsp;&nbsp;{{#if profile_image}}<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{profile_image}}<br>&nbsp;&nbsp;&nbsp;&nbsp;{{/if}}<br>{{/author}}</code><br><br>See the object attributes of <code>author</code> <a href=\"https://themes.ghost.org/docs/author-context#section-author-object-attributes\" target=_blank>here</a>.<br><br><code>{{#post}}<br>&nbsp;&nbsp;&nbsp;&nbsp;{{#if feature_image}}<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{feature_image}}<br>&nbsp;&nbsp;&nbsp;&nbsp;{{/if}}<br>{{/post}}</code><br><br>See the object attributes of <code>post</code> <a href=\"https://themes.ghost.org/docs/post-context#section-post-object-attributes\" target=_blank>here</a>.<br><br><code>{{#tag}}<br>&nbsp;&nbsp;&nbsp;&nbsp;{{#if feature_image}}<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{feature_image}}<br>&nbsp;&nbsp;&nbsp;&nbsp;{{/if}}<br>{{/tag}}</code><br><br>See the object attributes of <code>tags</code> <a href=\"https://themes.ghost.org/docs/tag-context#section-tag-object-attributes\" target=_blank>here</a>.",
      		"failures": [
      			{
      				"ref": "post.hbs",
      				"message": "Please remove or replace {{#if image}} from this template"
      			}
      		],
      		"code": "GS001-DEPR-CON-IMG"
      	},
      	{
      		"fatal": true,
      		"level": "error",
      		"rule": "Replace the <code>{{#if @blog.cover}}</code> helper with <code>{{#if @blog.cover_image}}</code>",
      		"details": "The <code>cover</code> attribute was replaced with <code>cover_image</code>.<br>Instead of <code>{{#if @blog.cover}}</code> you need to use <code>{{#if @blog.cover_image}}</code>.<br>See <a href=\"https://themes.ghost.org/docs/blog\" target=_blank>here</a>.",
      		"failures": [
      			{
      				"ref": "index.hbs",
      				"message": "Please remove or replace {{#if @blog.cover}} from this template"
      			},
      			{
      				"ref": "tag.hbs",
      				"message": "Please remove or replace {{#if @blog.cover}} from this template"
      			}
      		],
      		"code": "GS001-DEPR-CON-BC"
      	},
      	{
      		"fatal": true,
      		"level": "error",
      		"rule": "Replace the <code>{{#if author.image}}</code> helper with <code>{{#if author.profile_image}}</code>",
      		"details": "The <code>image</code> attribute in author context was replaced with <code>profile_image</code>.<br>Instead of <code>{{#if author.image}}</code> you need to use <code>{{#if author.profile_image}}</code>.<br>See the object attributes of <code>author</code> <a href=\"https://themes.ghost.org/docs/author-context#section-author-object-attributes\" target=_blank>here</a>.",
      		"failures": [
      			{
      				"ref": "partials/loop.hbs",
      				"message": "Please remove or replace {{#if author.image}} from this template"
      			}
      		],
      		"code": "GS001-DEPR-CON-AIMG"
      	},
      	{
      		"fatal": true,
      		"level": "error",
      		"rule": "Replace the <code>{{#if tag.image}}</code> helper with <code>{{#if tag.feature_image}}</code>",
      		"details": "The <code>image</code> attribute in tag context was replaced with <code>feature_image</code>.<br>Instead of <code>{{#if tag.image}}</code> you need to use <code>{{#if tag.feature_image}}</code>.<br>See the object attributes of <code>tags</code> <a href=\"https://themes.ghost.org/docs/tag-context#section-tag-object-attributes\" target=_blank>here</a>.",
      		"failures": [
      			{
      				"ref": "tag.hbs",
      				"message": "Please remove or replace {{#if tag.image}} from this template"
      			}
      		],
      		"code": "GS001-DEPR-CON-TIMG"
      	}
      ]
    """[39m

[37mThemeValidationError: The currently active theme "casper" is invalid.
    at ThemeValidationError.GhostError (/var/lib/ghost/versions/1.5.1/core/server/errors.js:9:26)
    at new ThemeValidationError (/var/lib/ghost/versions/1.5.1/core/server/errors.js:52:20)
    at /var/lib/ghost/versions/1.5.1/core/server/themes/index.js:51:43
    at tryCatcher (/var/lib/ghost/versions/1.5.1/node_modules/gscan/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/1.5.1/node_modules/gscan/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/var/lib/ghost/versions/1.5.1/node_modules/gscan/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/var/lib/ghost/versions/1.5.1/node_modules/gscan/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/var/lib/ghost/versions/1.5.1/node_modules/gscan/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/var/lib/ghost/versions/1.5.1/node_modules/gscan/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/var/lib/ghost/versions/1.5.1/node_modules/gscan/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/var/lib/ghost/versions/1.5.1/node_modules/gscan/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)[39m
[39m
[2017-08-09 14:05:14] [36mINFO[39m Ghost is running in production... 
[2017-08-09 14:05:14] [36mINFO[39m Your blog is now available on http://localhost:2368/ 
[2017-08-09 14:05:14] [36mINFO[39m Ctrl+C to shut down 
[2017-08-09 14:05:14] [36mINFO[39m Ghost boot 1.975s `

**Comment by DeciderWill** [comment]
Appears my issue with Casper is because you need to use /var/lib/ghost/content rather than /var/lib/ghost/content/

**Comment by pascalandy** [comment]
That's true:

> Appears my issue with Casper is because you need to use /var/lib/ghost/content rather than /var/lib/ghost/content/

I propose to close this :)

**Comment by eexit** [comment]
Hello,

I'm having an issue where I cannot mount local themes into the container. It looks likes the `content/themes` path isn't mapped:

```yaml
version: '2.1'
services:
  portfolio:
    image: ghost:1.17-alpine
    volumes:
      - ./content:/var/lib/ghost/content
      - ./config.development.json:/var/lib/ghost/config.development.json
    environment:
      DEBUG: ghost:*,ghost-config
```

The default casper theme shows up and a symlink appears into my local `content/themes`:

```sh
$ ll content/themes
lrwxrwxrwx  1 eexit staff   44 Nov 20 14:32 casper -> /var/lib/ghost/current/content/themes/casper
drwxr-xr-x 14 eexit staff  476 Nov 19 23:22 mytheme
```

I can't figure out why my theme `mytheme` doesn't show up in Ghost although it's valid. If I upload it, it works just fine.

Thanks,

**Comment by pascalandy** [comment]
@eexit 
The path you are looking for is /var/lib/ghost/versions/$GHOST_VERSION/content/themes

I personally prefer to build my own image and copy my theme(s) at this point. 

Have fun!

**Comment by eexit** [comment]
@pascalandy Are you saying that there's no way to map the `themes` directory?
Why do `data` and `images` directories mapped but not the `themes` dir?

**Comment by pascalandy** [comment]
> Are you saying that there's no way to map the themes directory? 
Correct

It's because of this https://github.com/docker-library/ghost/blob/master/1/alpine/Dockerfile#L37
There is a symlink into casper.

**Comment by eexit** [comment]
> There is a symlink into casper. 

Yes, I saw that but in my case, I want to include my own theme and have it synced with my host so I can develop it without the need to pack the theme every time I want to test it.

**Comment by tianon** [comment]
You should be able to mount it directly into `/var/lib/ghost/content/themes/xxx` -- is that not working?

**Comment by eexit** [comment]
Okay, I found a way:

```yml
version: '2.1'
services:
  blog:
    image: ghost:1.17-alpine
    volumes:
      - ./content:/var/lib/ghost/content
      - ./content/themes/mytheme:/var/lib/ghost/current/content/themes/mytheme
      - ./config.development.json:/var/lib/ghost/config.development.json
    environment:
      DEBUG: ghost:*,ghost-config
      NODE_ENV: development
```

If you want to completely map the `themes` directory (meaning you must have casper on your host):

```yml
version: '2.1'
services:
  blog:
    image: ghost:1.17-alpine
    volumes:
      - ./content:/var/lib/ghost/content
      - ./content/themes:/var/lib/ghost/current/content/themes
      - ./config.development.json:/var/lib/ghost/config.development.json
    environment:
      DEBUG: ghost:*,ghost-config
      NODE_ENV: development
```

**Comment by ewliang** [comment]
@eexit OMG Downloading the casper theme to my host directory worked! Ghostjs bad documentation. I've been stuck with this issue for days lol.
