### ISSUE TITLE
Looking for best practice to update the official Ghost / Ghost CLI image

### ISSUE THREAD

**Issue by pascalandy** [docker-library/ghost#79]
Hi,

I was about to fork and submit a PR for Ghost/Ghost CLI updates. But I know the Docker team have good process to update all your official images on a regular base. So it made me wonder…

### Observation 1)

I see the docker-library-bot seems to catchup with Ghost updates ([per example](https://github.com/docker-library/ghost/commit/3989f7fc344559a0d65208a56ddf1adc1b7753ac)) but didn't catch the Ghost CLI update.

Ghost [release](https://github.com/TryGhost/Ghost/releases) shows 1.6.1
Ghost CLI [release](https://github.com/TryGhost/Ghost-CLI/releases) shows 1.1.0

### Observation 2)

I see that the Dockerfile for Ghost 1.6.0 was updated more than 24 hours ago, but in the [docker hub tags](https://hub.docker.com/r/library/ghost/tags/) the image is not there. Same story for 1.6.1

### My question

I want to know what would be the best way to contribute regarding Ghost future updates.

Cheers!
Pascal

**Comment by yosifkit** [comment]
The Ghost CLI update was only 2 hours ago and the Jenkins job for the docker-library-bot only runs 4 times a day to run the `update.sh` script.  If there is an immediate/important security update @tianon and I can trigger it as necessary.

For updating tags on the Docker Hub, that requires a PR to official images to update the `library/ghost` file.  I have https://github.com/docker-library/official-images/pull/3336 which contains the ghost 1.6.1 bump.  It was just merged, so the images will be pushed to the Docker Hub shortly.

For future updates, if you see a version bump here but no PR in official-images, then feel free to make one. It is as easy as piping the output of `generate-stackbrew-library.sh` in the ghost repo to the `library/ghost` file in the official-images repo.

**Comment by pascalandy** [comment]
Great. I guess I was too quick on this one :-p

Thank you!
