### ISSUE TITLE
Logs are getting bigger and bigger

### ISSUE THREAD

**Issue by pascalandy** [docker-library/ghost#80]
[This](https://github.com/docker-library/ghost/blob/3989f7fc344559a0d65208a56ddf1adc1b7753ac/1/alpine/Dockerfile#L12) is new in Ghost v1

I feel this is overkill for most installations. In 7 days, the size of my logs in prod is about **140 MO**.

@acburdine can you points us to some docs about the level of the log we can collect? 
I looked in https://docs.ghost.org/v1.0.0/docs/cli-log#section-options and there is no mention of this. 

Cheers!
Pascal

**Comment by pascalandy** [comment]
I found this from the npm [docs](https://docs.npmjs.com/misc/config).

## loglevel

```
Default: "warn"
Type: String
Values: "silent", "error", "warn", "http", "info", "verbose", "silly"
```

I think it would make sense to use `error` instead of `warn`.
We could also add this info as a comment in the Dockerfile.

Make sense?

**Comment by tianon** [comment]
Does Ghost itself read the `NPM_CONFIG_LOGLEVEL` environment variable? (that seems odd)

**Comment by tianon** [comment]
https://docs.ghost.org/v1.0.0/docs/config#section-logging seems to be the relevant config section

**Comment by tianon** [comment]
So, something like `-e logging__level=error` should do the trick; testing now.

**Comment by tianon** [comment]
Yep, works great!
```console
$ docker run -it --rm --name ghost -e logging__level=error ghost:1-alpine
[2017-08-21 22:37:23] INFO Finished database migration! 

```

(I've already sent several requests to this instance, and there are no logs for the events.)

**Comment by pascalandy** [comment]
What you POV about using `error` in prod @tianon ?

**Comment by tianon** [comment]
My opinion is that folks should choose what makes sense for themselves, and
that our image ought to not deviate from the defaults provided by upstream
without strong rationale.

**Comment by SISheogorath** [comment]
The reason why default is `warn` is because the default `NODE_ENV` is also `development`. So the image itself is currently in the same context. It is a development setup. Not a production setup. (But changing that only takes 2 env vars)

**Comment by pascalandy** [comment]
Hey @SISheogorath 
[Here](https://github.com/docker-library/ghost/blob/master/1/alpine/Dockerfile#L13) we can see that NODE_ENV = production. 

I guess I'm missing something here:

> The reason why default is warn is because the default NODE_ENV is also development.

**Comment by SISheogorath** [comment]
@pascalandy Looks like I missed that ^^ I was totally sure that it's still `development`. In this case, it makes sense to modify the loglevel, too. Maybe creating an upstream issue that changes the default loglevel for `production` would be useful.

**Comment by tianon** [comment]
Indeed, I think this should be taken up with upstream to see what their opinion would be about changing the default `loglevel` for production to something less verbose. :+1:
