### ISSUE TITLE
URL in Dockerfile are not configurable.

### ISSUE THREAD

**Issue by uname-yang** [docker-library/ghost#86]
I found the url in docker are static.  `http://localhost:2368`.

```
su-exec node ghost config --ip 0.0.0.0 --port 2368 --no-prompt --db sqlite3 --url http://localhost:2368 --dbpath "$GHOST_CONTENT/data/ghost.db";
```
When we click some <a> tag in html, it will redirect to 'http://localhost:2368'.
![capture](https://user-images.githubusercontent.com/8829072/29902216-3faca39c-8e2f-11e7-8956-7a492874ab4b.PNG)
But in host server, we need to change it to hostname, such as 'www.xxx.com'.
And there is not configurable.

**Comment by tianon** [comment]
Use "-e url=..." to change that value at runtime.

**Comment by tianon** [comment]
See also https://github.com/docker-library/ghost/issues/77.

**Comment by tianon** [comment]
FYI, I've filed https://github.com/docker-library/docs/pull/1306 to help clarify this. :+1:
