### ISSUE TITLE
Error detected in the development configuration.

### ISSUE THREAD

**Issue by karai17** [docker-library/ghost#91]
```
$ docker run -it -v "/home/blog/ghost/content:/var/lib/ghost/content" --rm ghost:latest ghost start --development
```

```
✖ Validating config
A ConfigError occurred.

Error detected in the development configuration.

Message: Config file is not valid JSON

Debug Information:
    Node Version: v6.11.3
    Ghost-CLI Version: 1.1.1
    Environment: development
    Command: 'ghost start --development'

Please refer to https://docs.ghost.org/v1/docs/troubleshooting#section-cli-errors for troubleshooting.
```

**Comment by tianon** [comment]
This is likely because the image does not include a development mode
configuration file at all (we only supply a "production" mode configuration
file).

**Comment by karai17** [comment]
That would do it. Is there a specific reason why you don't support a dev mode? It's far easier to just load up a docker container than to manually install a bunch of stuff to develop on. I really think a simple dev mode would be very useful, even if it is not the default run mode.

**Comment by acburdine** [comment]
@karai17 so the docker image has been configured _not_ to use `ghost start`, because ghost start would launch ghost in a child process, and then exit, which would stop the container.

If you're wanting to use the docker image to start ghost in development, what you _could_ do is specify things with environment variables, e.g.

```
docker run -it -v "/home/blog/ghost/content:/var/lib/ghost/content" -e NODE_ENV=development --rm ghost:latest
```

**Comment by karai17** [comment]
Thanks for the info. I just learned about using the env variables last night after spending hours trying to mess with this image to do my bidding (the url was showing up as `localhost:2368` despite my best efforts) only to find the answer buried in a github issue.

I highly recommend adding info about using the end variables to the readme so that people new to ghost/node/etc are able to configure things a bit quicker. :)

**Comment by tianon** [comment]
See https://github.com/docker-library/docs/pull/1018/files#diff-d5b3640a478d2d85406ab914762265a5 :+1:
