### ISSUE TITLE
Can't run development mode for theme building without overrides

### ISSUE THREAD

**Issue by zackify** [docker-library/ghost#99]
See this post I wrote: https://zach.codes/ghost-theme-development-with-docker/ You can't set development mode without also adding a new config file. If it was there by default, it wouldn't need to be overwritten

**Comment by tianon** [comment]
@acburdine what do you think about also generating `config.development.js`?  This keeps coming up again and again. :sweat_smile:

**Comment by tianon** [comment]
Just doing `ln -s config.production.json config.development.json` appears to work appropriately, so perhaps that's all that's needed?

**Comment by zackify** [comment]
yessss this would solve the problem :D
